### ISSUE TITLE
Error adding winrm agent on windows

### ISSUE THREAD

**Issue by emilfazzi** [glpi-project/glpi-agent#350] opened 2023-02-23 11:17 UTC
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

When adding new winrm remote agent in windows with the following command, it returns the error:

**Command:**
`winrm://<user>:<password>@<ip>?=mode=ssl --target server0 --no-ssl-check --debug --debug`

**Error:**
```
[debug] Failed to load GLPI::Agent::Task::RemoteInventory::Remote::Winrm module: Can't locate GLPI/Agent/SOAP/WsMan.pm in @INC (you may need to install the GLPI::Agent::SOAP::WsMan module) (@INC contains: C:/Program Files/GLPI-Agent/perl/agent ./lib C:/Program Files/GLPI-Agent/perl/site/lib C:/Program Files/GLPI-Agent/perl/vendor/lib C:/Program Files/GLPI-Agent/perl/lib) at C:/Program Files/GLPI-Agent/perl/agent/GLPI/Agent/Task/RemoteInventory/Remote/Winrm.pm line 14.
BEGIN failed--compilation aborted at C:/Program Files/GLPI-Agent/perl/agent/GLPI/Agent/Task/RemoteInventory/Remote/Winrm.pm line 14.
Compilation failed in require at C:/Program Files/GLPI-Agent/perl/agent/GLPI/Agent/Task/RemoteInventory/Remote.pm line 48.
[error] Skipping 'winrm://<user>:<password>@<ip>?=mode=ssl' remote class loading failure
```

### To reproduce

1. Install [GLPI-Agent 1.4](https://github.com/glpi-project/glpi-agent/releases/download/1.4/GLPI-Agent-1.4-x64.msi) on windows 
2. Add a remote with the given command

### Expected behavior

Add the remote with no errors

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### Additional context

Workaround has been applied by manually inserting the file [WsMan.pm](https://github.com/glpi-project/glpi-agent/blob/develop/lib/GLPI/Agent/SOAP/WsMan.pm) in the correct location (`GLPI-Agent\perl\agent\GLPI\Agent\SOAP\`)

**Comment by g-bougard** [comment] 2023-02-23 11:24
Hi @emilfazzi 
this problem has still been fixed in nightly builds: try it from there https://nightly.glpi-project.org/glpi-agent/
So I'm closing, but feel free to reopen if you find the problem is not fixed in nightly.

**Closed as completed by g-bougard** 2023-02-23 11:24 UTC
Labels: bug

**Comment by emilfazzi** [comment] 2023-02-23 13:03
Hi @g-bougard
When will the next stable build be released?
Thank you!

**Comment by g-bougard** [comment] 2023-02-23 13:29
There's still no planed date for the release as we are still in the process of renewing the SSL certificate to sign windows MSI packages. For really obscure reason, this process is long and unpredictable... As soon as the renew will occur, we will plan the 1.5 release.
Actually a lot of people is still using nightly build as this is what would be next release and they need fixed features.
And the advantage of nightly builds is also to permit an early detection of bugs.

**Comment by emilfazzi** [comment] 2023-04-04 15:26
Hello @g-bougard 
I apologize for the bother... Are there any news about the 1.5 release date?
Thank you for the support!

**Comment by g-bougard** [comment] 2023-04-04 15:29
Hi @emilfazzi 
sorry, this seems really hard to obtain that code signing certificate.
Don't expect the next release before a month.
