### ISSUE TITLE
Request to scan inventory

### ISSUE THREAD

**Issue by EC2311** [glpi-project/glpi-agent#98] opened 2022-04-19 11:47 UTC
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

GLPI Agent 1.2
GLPI V10 RC3

I want to request an inventory of a laptop

in the log file of the agent i've got a strange communication
![image](https://user-images.githubusercontent.com/42341169/163996461-4425c17b-f9ba-42b5-9771-0b56ee6c2aa4.png)

no scan is run.

### To reproduce

Computer
Request an inventory

in the file log of the agent : 
![image](https://user-images.githubusercontent.com/42341169/163996518-245a9a5f-cca6-4126-bf07-8f729696f74d.png)

### Expected behavior

The scan should run

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

10.0.0-rc3

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0-rc7

**Comment by g-bougard** [comment] 2022-04-20 06:35
Hi @EC2311 

GLPI Agent has an embedded light HTTP server which offers an interface for few functions like forcing a run from a local browser or from the GLPI server when GLPI server can reach it (see [HTTP interface dopcumentation](https://glpi-agent.readthedocs.io/en/latest/plugins/index.html)).

The logged lines are only showing a http client is trying "weird" request on that agent interface and the agent reports them as error as the requested "weird" path is not supported by the agent.

If you want to identify the faulty http client, you should enabled debug2 in configuration setting `debug = 2` and restart the service. You should then also see the requester ip. Maybe some service in your network are doing random http requests while scanning the network.

Anyway, these requests won't involve anything with the agent but that error lines in log. If you identify the source, you can create some firewall rules to block them or even limit the port access to only trusted clients: probably just localhost and glpi server.

But you're talking about "requesting an inventory of a laptop" so maybe I missed something. What are you trying to do when doing the request ? If you're effectively using a http client and see that error lines at that moment, this is another problem and then you should tell us: what http client you're using (probably a browser but which one?) and what URL you're using for the request ?

**Comment by EC2311** [comment] 2022-04-20 06:52
Hi @g-bougard 

In fact i request an inventory for the laptop from glpi server (localhost/glpi) which hosts glpi in V10 RC3.
![image](https://user-images.githubusercontent.com/42341169/164167959-b00f1129-2cbb-4c6b-b4fb-26130bfc7619.png)

**Comment by EC2311** [comment] 2022-04-20 06:57
The tag (which is present in registry of the agent) is not present in the file when we do the command : glpi-inventory.bat >c:\pc.txt 

so the laptop had been created in the root rather in the right entity.

**Comment by g-bougard** [comment] 2022-04-20 07:16
If you're requesting the inventory for the agent on the localhost, you still have to enable debug2 to see what's going on with the agent service. On windows, you should change the value in registry at `HKLM\Softwares\GLPI-Agent\debug` and restart the service, then try to request inventory and check the `C:\Program Files\GLPI-Agent\logs\glpi-agent.log` file.

From a browser on the laptop, you should also be able to access: `http://localhost:62354/` as explained in the doc I pointed to you.

About you `glpi-inventory.bat` command, this command won't read your configuration in registry. So you have to:
 * run `glpi-agent.bat --local C:\` so it reads you current config,
 * or add `--tag YOUR-TAG` option to `glpi-inventory.bat` command

**Comment by EC2311** [comment] 2022-04-20 08:17
I know that I can force an inventory from laptop itself using the localhost:62354 url ;) 
but we can do it too from glpi server 
and in this case there is a problem

here is the snapshot from the log after set in debug 2 the agent 
![image](https://user-images.githubusercontent.com/42341169/164182984-411eedd1-efa0-4f30-a351-b65c09e923c0.png)

ok for the tag

**Comment by g-bougard** [comment] 2022-04-20 08:57
Do you really have 5 servers setup in your `server` agent configuration ? This is really weird, even if this is authorized by design.

It seems the server remained "untrusted" and this probably means the agent failed to resolved your 5 servers adresses. The glpi server probably tried few different ips (the ones it knows for the agent) and the last one generated the error. That's still weird and I don't see what's going on with this last request.

Anyway, you should probably have to configure your glpi server ip in the `httpd-trusted` configuration parameter.

**Comment by EC2311** [comment] 2022-04-20 09:31
on my config I have : 
![image](https://user-images.githubusercontent.com/42341169/164196756-ac3a5ba7-8722-49b3-95fa-fdd10c532628.png)
knowing that the request is coming from localhost server.. which is 127.0.0.1...

I will remove some servers (to test link glpi v10 with agent 1.2) 

nevertheless, I did a test with an old glpi (9.5.5) to request inventory on the same agent (glpi agent 1.2) : I have no error : inventory is well done.

So : perhaps a missmatch in serverside glpi v10 ?

**Comment by g-bougard** [comment] 2022-05-10 07:34
Hi @EC2311 

you originally opened this issue while using GLPI10 rc release. Have you tried with final release ?
If yes and you still have an issue, can you open a new issue on glpi project as this seems to be a server issue (and as this seems to work when you're using glpi 9.5.5).
So I'm closing this one but feel free to comment and link a glpi issue to this one for the history.
Thank you for your involvement.

**Closed as completed by g-bougard** 2022-05-10 07:34 UTC
Labels: question
