### ISSUE TITLE
Remote Management - MeshCentral 

### ISSUE THREAD

**Issue by rjt** [glpi-project/glpi-agent#135] opened 2022-06-05 23:01 UTC
### Documentation

Yes, I read it

### Professional support

I still have but want a public following to inform the community

### Expected behavior

Clicking on a computer in the GLPI web interface would have an option to link directly to the same machine in my own MeshCentral server to  remotely monitor or control via RDP, but also power on, power off, boot to AntiVirus scan, and upgrade the BIOS.  

### Alternatives you've considered

TeamViewer and Supremo, but i want everything self-hosted because i do not trust cloud providers to not be compromised.  

### Additional context

![image](https://user-images.githubusercontent.com/360343/172073884-79f15972-07e3-4359-9290-3cb16a6a9c40.png)
[MeshCentral.com](https://meshcentral.com/) is an intel sponsored  [opensource Remote Management  project here on github](https://github.com/Ylianst/MeshCentral) that leverages vPro when available, but vPro hardware is NOT required and yes it works with AMD systems and it even works with the [RaspberryPi](url).  vPro hardware is very similar to HP iLO, IPMI, Dell iDrac.  vPro hardware has been  included on almost all corporate laptops and desktops since at least 2008, but even many IT people are not aware of what it can do.    With vPro hardware, the remote desktop endpoint can be powered off, but it can be powered on remotely via your own  MeshCentral server.  The IT department can have the Desktop boot up with a particular ISO to say do an offline anti-virus scan or wipe and reload the desktop OS.  RDP is built-in.  WebRTC is built-in to transfer files.  

The principal author @Ylianst makes great simple to follow videos  **[very quick to setup the opensource MeshCentral server](https://www.youtube.com/watch?v=GsQbWZmRRAU)** on a Linux or Windows server with NODE js installed.   
   1. `npm install meshcentral`
   2. `node node_modules/meshcentral `

MeshCentral continues to be under very active development.  

[vPro](https://en.wikipedia.org/wiki/Intel_vPro)  is also known as ActiveManagementTechnology or AMT and there several names for the components involved.  If your Desktop has a vPro logo, the hardware is definitely built-in.

**Comment by g-bougard** [comment] 2022-06-06 12:20
Hi @rjt 
thank you for your request. It seems really interesting to have this support. I'll try to investigate and develop this support in GLPI Agent v1.4 I think.
Stay tuned if I've nightly build for you to test.

**Comment by shadrinid** [comment] 2022-06-08 11:59
It would also be very interesting to see the possibility of remote connection via VNC.

**Comment by miguelanruiz** [comment] 2022-06-29 23:07
Hi Guillaume,

I have been inspecting how to reproduce some remote access based on Device Remote Desktop and Device terminal. All information was checked from:

> 14. Embedding MeshCentral on MeshCentral2UserGuide-0.2.6
> Link: https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.6.pdf

And it looks very simple, what GLPI have to inventory is 
```
C:\Program Files\Mesh Agent\MeshAgent.exe -nodeid (MSWin32)
/usr/local/mesh_services/meshagent/meshagent -nodeid (Linux)
```

Output should be a string like that:

> F67A506D6EB1C378D8XXXXXAA12125AF5349FF15C2XXXXXXXF022A5D7307026B4D76B30E828105E66FF02D86BC

That we have to take in account is how start procedure of authentication in order to get access maybe from a GLPI frontend, regarding to this doc says:
![image](https://user-images.githubusercontent.com/49277353/176556113-6aaf8d5e-581e-4207-85ca-af2b6f61455c.png)

If you over MeshCentral control panel, generate a token based on user- password pair, then GLPI or **Business Web Page** have to use an iframe with source:

![image](https://user-images.githubusercontent.com/49277353/176557714-72ad8607-3b16-4a00-968c-99e1bd151ad0.png)
Output from this will give you user-password pair
`https://MESHCENTRAL/?user=XXXX&pass=XXXXXX&gotonode=<!--MACHINE_NODEID:Got by Agent>&viewmode=XX&hide=XX`

Where **viewmode** will provide what type of control you access and **hide** is present in order to not show some layout elements

![image](https://user-images.githubusercontent.com/49277353/176557016-ff2cda4a-17be-46e2-a60b-c5a6cbdcb690.png)

I consider that **hide** param always should be 31. If you did that well will get an iframe as next one:

![image](https://user-images.githubusercontent.com/49277353/176557230-f2a85d3f-186a-46c2-8785-fc5ccc8323f8.png)

Before to launch your first remote control its needed to set this params on config.json of your platform, it allows that you can use the iframe from GLPI or **Business Web Page** :

```
"settings": {
    "AllowLoginToken": true,
    "AllowFraming": true
}
```
Regarding to Intel® AMT or vPro, i could provide some labs in order to inventory this information, i think just is 
![image](https://user-images.githubusercontent.com/49277353/176558785-cc33ab75-b7e9-4d33-8337-533deaebabe3.png)
> - Profile: (CCM Client Control Mode or ACM Admin Control Mode (unattended by user))
> - Trusted DNS
> - Wired or Wireless Enabled mode
> - Client Initiated Remote Access CIRA channel config (it provides connection to Remote provisioning server)
> - Trusted CA Hash (It can be self signed or from CA class 2)

Some related doc:
- https://www.intel.com/content/dam/support/us/en/documents/technologies/remote-configuration-certificate-selection.pdf
- https://vpro.by/intel-amt-kvm-vnutrennee-ustroystvo-i-nastroyka
- https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm?turl=WordDocuments%2Frootcertificatehashes.htm

It may be a more future-oriented extension (**AMT inventory**) because it is not as common due to cost and because meshcentral uses an additional utility to generate this detail. 
![image](https://user-images.githubusercontent.com/49277353/176560115-0579a4ec-d65d-4792-8eab-b82f96c3ce6e.png)
Link: https://meshcentral.com/info/docs/MeshCmdUserGuide.pdf


Now, thing is that im looking for documentation about Developer guide of GLPI Agent, but I have not found it, is it ready and public?

**Comment by miguelanruiz** [comment] 2022-06-29 23:54
Hi @g-bougard ,

It works on Agent side:

```
package GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt::MeshCentral;

use strict;
use warnings;

use parent 'GLPI::Agent::Task::Inventory::Module';

use English qw(-no_match_vars);

use GLPI::Agent::Tools;

sub isEnabled {
    return OSNAME eq 'MSWin32' ?
        canRun("C:\\Program Files\\Mesh Agent\\MeshAgent.exe") :
        canRun('/usr/local/mesh_services/meshagent/meshagent');
}

sub _getNodeId {
    return OSNAME eq 'MSWin32' ?
    getFirstLine(
        command => 'C:\\Program Files\\Mesh Agent\\MeshAgent.exe -nodeid') :
    getFirstLine(
        command => '/usr/local/mesh_services/meshagent/meshagent -nodeid');
}

sub doInventory {
    my (%params) = @_;

    my $inventory = $params{inventory};
    my $logger    = $params{logger};

    my $nodeId = _getNodeId();

    return unless $nodeId;

    $inventory->addEntry(
        section => 'REMOTE_MGMT',
        entry   => {
            ID   => $nodeId,
            TYPE => 'meshcentral'
        }
    );
}

1;
```

Saved over path:

> /GLPI/Agent/Task/Inventory/Generic/Remote_Mgmt/MeshCentral.pm

¿Do you think can be included to project?

**Comment by g-bougard** [comment] 2022-06-30 08:06
Hi @miguelanruiz,

yes, your code is clearly a good candidate for integration. Do you feel easy to create a PR so your code will directly attributed to you ? Let me know if you prefer I directly add it via a commit with attribution to you in comment.

It'll add unittests, thanks to your previous post.

I want also to discuss a point about security. After a quick read of the previous post, I'm not sure to fully understand the way of initiating a remote management session. Is the nodeid sufficient to have a direct access to the computer ? Or will people still have to enter a password somewhere like for teamviewer ? In fact with the URL you're showing: `https://MESHCENTRAL/?user=XXXX&pass=XXXXXX&gotonode=<!--MACHINE_NODEID:Got by Agent>&viewmode=XX&hide=XX`, could user and pass be requested by GLPI or is this one thing a user have to do before by himself ? Can I guess also `MESHCENTRAL` is a private url ? If yes, it should probably need a dedicated GLPI plugin which will handle the configuration.

**Comment by miguelanruiz** [comment] 2022-06-30 16:00
Hi Guillaume,

I can do PR no problem, just give me 3 hours around to put it. If you consider is needed to add or improve something you are free to do it. 
Regarding to remote session, nodeid is sufficient to have console or remote desktop access, if you supress user and pass from url.

If you generate a token, you can add this credential to URL and get access directly without have to enter a password somewhere like for teamviewer. Else you can use this URL maybe as a popup or new browser window:
```
> MeshCentral then will ask you credentials.
https://MESHCENTRAL/?gotonode=<!--MACHINE_NODEID:Got by Agent>&viewmode=XX&hide=XX
> MeshCentral will enter directly, passed by GLPI can be.
https://MESHCENTRAL/?user=XXXX&pass=XXXXXX&gotonode=<!--MACHINE_NODEID:Got by Agent>&viewmode=XX&hide=XX
```
With next params you will get:
```
> Will give you access to Remote desktop control.
&viewmode=11&hide=31
> Will give you access to Terminal control.
&viewmode=12&hide=31
```

Both methods include controls for shutdown, reset...
![image](https://user-images.githubusercontent.com/49277353/176723378-c44f844e-3d1c-48f6-bff2-b537eb507b57.png)

Yes sr, MESHCENTRAL is private URL.

¿Do you think instead plugin, just can be a new tab on General panel of GLPI Inventory?
![image](https://user-images.githubusercontent.com/49277353/176723951-760d68d5-35e2-428b-8d7c-df2e817306ff.png)
 
Cause only is a URL, maybe can include user-password form and no more.

Best regards,

**Comment by g-bougard** [comment] 2022-06-30 16:10
> Regarding to remote session, nodeid is sufficient to have console or remote desktop access, if you supress user and pass from url.
Do you mean you can manage the computer without knowing user+pass but just knowing the nodeid if you can request the MESHCENTRAL private url ? Or you still have to authenticate at some time later ?

> ¿Do you think instead plugin, just can be a new tab on General panel of GLPI Inventory?
A plugin can just add such a panel entry. In that case, I guess it should even be named "Mesh Central".

**Comment by miguelanruiz** [comment] 2022-06-30 16:18
If you without knowing user+pass access to url then MeshCentral will ask you login credentials before start session.
> Just if you use this format:
> https://MESHCENTRAL/?gotonode=<!--MACHINE_NODEID:Got by Agent>&viewmode=XX&hide=XX
> <img width="462" alt="image" src="https://user-images.githubusercontent.com/49277353/176727259-7f396efd-4075-41b3-92e5-ffefbae8725a.png">

A plugin can just add such a panel entry. In that case, I guess it should even be named "Mesh Central". Its okay for me sr.

**Comment by fernandobayit** [comment] 2022-07-02 16:17
just remembering that these paths can change, since meshcentral is fully customizable. It would be important to consider this 
variable so that automation is maximized in the best possible way.
for example:
Windows OS => 'C:\\Program Files\\Business_Name\\agent_custom.exe -nodeid') :
Linux OS => '/usr/local/mesh_services/Business_Name/agent_custom -nodeid');

**Comment by g-bougard** [comment] 2022-07-12 08:30
The PR #163 was just merged to answer this feature request.
Thank you @miguelanruiz for having worked on that support.

**Closed as completed by g-bougard** 2022-07-12 08:30 UTC
Labels: enhancement

**Comment by Smiley-k** [comment] 2025-03-29 14:11
I think I will continue this topic rather than open a new one, for some reason the ID does not work on linux machines, i.e. if you run the command in the console, it will show the ID `/usr/local/mesh_services/meshagent/meshagent -nodeid (Linux)` , but if you do as in this topic https://github.com/glpi-project/glpi/issues/19313 , then in the remote management section on linux OS the ID is not displayed, only displayed on windows OS

**Comment by g-bougard** [comment] 2025-03-31 07:10
Hi @Smiley-k 

I'm sorry, but this issue is closed since years. If you want a follow on an update, you have to open a new issue.
