### ISSUE TITLE
I can't request inventory on the server to the agent

### ISSUE THREAD

**Issue by krenaudUR** [glpi-project/glpi-agent#118] opened 2022-05-10 08:51 UTC
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

Yes, I know

### Is your help request related to a problem?

I can't request inventory here :
![Agent](https://user-images.githubusercontent.com/105273801/167582934-3b58a6bb-9dba-4edd-b7a9-7f5340ad10d1.png)

The server is on GLPI 10 on debian 11. The Agent is version 1.2. The agent succeed to send to server the inventory.
Here's the configuration of the agent : 
![AgentConf](https://user-images.githubusercontent.com/105273801/167586357-9b30eff6-2e93-454b-878d-4376b2d57f10.png)

I have put "Debug" on "2" but I can't see the request of the server on the log.

I use also the following plugin : 
![Plugin](https://user-images.githubusercontent.com/105273801/167587248-2b0dbbb6-ad34-4dd5-993d-309989bca73b.png)

The localhost address to force the upload of inventory work while physically on the pc with the agent on it.

So Agent > Server work
But Server > Agent doesn't work

### Expected behavior

That the request of asking inventory go to agent and update the information on the server

### Actions you've considered

I tried to adjust parameters on the registry but still the same problem. I read also the documentation but It seems I don't see anything about request to agent the inventory with what to do if it doesn't work.

### Additional context

The agent is on a pc who is using a proxy but the address of glpi to upload the inventory has been authorised on the proxy.
The agent use a .pem to communicate with the server that is working.

I'm French so sorry if some sentences are not correct. Don't hesitate to ask me more informations or tell me if I was not clear.
Thanks

**Comment by g-bougard** [comment] 2022-05-10 09:30
Hi @krenaudUR 
you're explaining the agent is using a proxy. Does this mean it is behind a firewall from the GLPI server point of vue ?

The GLPI feature to request an inventory only works if the GLPI server can reach directly the GLPI Agent IP address on its HTTP interface port. To check if the agent is reachable, get the ip reported in GLPI for the computer where is installed the agent and try from a console to reach the address `http://<IP>:62354/status` URL using curl or wget on a server console. This is indeed what is done by the refresh button near "Statut de l'agent", but you'll probably obtain a clear error from the console if the agent is not reachable.

**Comment by krenaudUR** [comment] 2022-05-10 10:56
Hi @g-bougard 
GLPI is also behind a proxy. It's clearly the proxy the problem because I see that : 
So when I do curl I have error that the connection it's denied by the access control. So I checked the log on the "Squid 4.6" the proxy with a grep of :62354 and all the request are denied. So I need to authorize that but I don't know what to put, because the url change because of the IP and I can't authorize this url http://"Star":62354/status because "Star" is not accepted on the proxy.  Do you have and idea of what can I do ?

**Comment by dsiens** [comment] 2022-05-10 11:20
Hello,
what I see of your registry entrie "server" i that the server is wrong

Must be : http://server/front/inventory.php

**Comment by krenaudUR** [comment] 2022-05-10 11:24
> Hello, what I see of your registry entrie "server" i that the server is wrong
> 
> Must be : http://server/front/inventory.php

Hello, 
it's not wrong because I'm following the documentation when you use glpiinventory :
![docglpiagent](https://user-images.githubusercontent.com/105273801/167617591-d6507145-3361-4b16-8c5c-905d420e7490.png)

**Comment by dsiens** [comment] 2022-05-10 11:34
La doc est peut être dépréciée...
La doc que j'ai suivi : https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html#command-line-parameters

 **SERVER="http://itms.acme.org/glpi/front/inventory.php"**

Est ce que le poste est remonté dans ton inventaire avec ton url "server" actuelle?
Sinon, essaye quand même mon url. Chez nous ça marche comme ça.

**Comment by krenaudUR** [comment] 2022-05-10 11:43
> La doc est peut être dépréciée... Est ce que le poste et remonté dans l'inventaire avec ton url actuelle? Sinon, essaye quand même mon url. Chez nous ça marche comme ça.

Le problème n'est pas au niveau de l'url du serveur de toute façon je vois très clairement que c'est le proxy qui me bloque pour les requête Serveur > agent
![proxydeny](https://user-images.githubusercontent.com/105273801/167620681-d93f23d5-76b7-4185-a803-2d3ce1d295fb.png)

maintenant faut que je trouve quel ligne acl à rajouter pour l'autoriser mais je sais pas trop encore la

**Comment by g-bougard** [comment] 2022-05-10 12:11
@krenaudUR is right, the problem is not the server url setup on agent side. He read the right documentation and he uses /plugins/glpiinventory as he probably manually installed GlpiInventory plugin.

@krenaudUR anyway you have a proxy configuration problem from server to agent? This is nor a GLPI Agent issue nor a GLPI server issue.
So I'm closing the issue, but feel free to comment is you find a solution and in the case this can help other people.
You may also want to open a thread in the GLPI forum. Maybe people there can help too.

**Closed as completed by g-bougard** 2022-05-10 12:11 UTC
Labels: help wanted

**Comment by krenaudUR** [comment] 2022-05-11 10:53
So It was a network and proxy problem the proxy was set in internal but I didn't need it so I put NO_PROXY and no_proxy in /etc/environnement of the glpi server. But curl seems to ignore that. So I need to put when I try do to a command curl : "curl --noproxy "Star" http://IP:62354/status" And I see the log on the client replying with a response status 200. But I imagine on the web interface it's doing a curl classic command without argument and so It's doesn't work. Can I do something about this ? @g-bougard

**Comment by krenaudUR** [comment] 2022-05-11 11:18
UPDATE : I found out in /glpi/src/agent.php line 607 it's telling to add a string of proxy to the command to check agent status or to force inventory of the agent if in glpi setting if there is a proxy setting defined. But I can't delete the proxy setting in glpi, because if I do that I can't reach external server like glpi network. So I have commented line 607 to 614. And nows it's working great :
![glpiagentworking](https://user-images.githubusercontent.com/105273801/167837022-7d576103-f825-409c-9668-588032521ded.png)

**Comment by g-bougard** [comment] 2022-05-11 11:37
Hi @krenaudUR 
thank you for the update. Probably the requestAgent() method should not have to use the same proxy configuration as that proxy configuration is named "Proxy configuration for upgrade check" in "General setup" in the system config form. We should probably add a proxy configuration setup in inventory configuration which may default to the general setup one but which could be disabled or changed to another one.

**Comment by krenaudUR** [comment] 2022-06-02 13:02
> UPDATE : I found out in /glpi/src/agent.php line 607 it's telling to add a string of proxy to the command to check agent status or to force inventory of the agent if in glpi setting if there is a proxy setting defined. But I can't delete the proxy setting in glpi, because if I do that I can't reach external server like glpi network. So I have commented line 607 to 614. And nows it's working great : ![glpiagentworking](https://user-images.githubusercontent.com/105273801/167837022-7d576103-f825-409c-9668-588032521ded.png)

EDIT : It's now line 533 to 542 in GLPI 10.0.1

**Comment by krenaudUR** [comment] 2025-10-01 13:45
@g-bougard Hi, do you know the line that needs to be commented (in /glpi/src/agent.php) for GLPI 11 for ignoring the proxy? The line seems to have changed completely.

**Comment by g-bougard** [comment] 2025-10-02 10:13
Hi @krenaudUR 

the requestAgent() API now uses getGuzzleClient() API one from src/Toolbox.php which is shared with other GLPI parts...

The lines are now into that getGuzzleClient() API. But if you disable them, this will also impact marketplace access and few other requests.

You have now to do more clever things, like passing an option to disable the proxy only for agent requests.

**Comment by krenaudUR** [comment] 2025-10-02 10:22
> Hi [@krenaudUR](https://github.com/krenaudUR)
> 
> the requestAgent() API now uses getGuzzleClient() API one from src/Toolbox.php which is shared with other GLPI parts...
> 
> The lines are now into that getGuzzleClient() API. But if you disable them, this will also impact marketplace access and few other requests.
> 
> You have now to do more clever things, like passing an option to disable the proxy only for agent requests.

Ah, it's annoying... I'm blocked now because of that. I'm forced to disable proxy to request inventory and then put it back for the moment (as the proxy is used for marketplace and plugin importmanufacturer). I hope it doesn't block the agent who sends inventory automatically.

**Comment by g-bougard** [comment] 2025-10-02 10:30
Do you think you can set NO_PROXY environment variable into your httpd server env to disable proxy for agents ?
If yes, can you try the following patch and set NO_PROXY environment variable for your web server ?
```php
diff --git a/src/Toolbox.php b/src/Toolbox.php
index d3d4c0e567..94bc80db31 100644
--- a/src/Toolbox.php
+++ b/src/Toolbox.php
@@ -1337,7 +1337,16 @@ class Toolbox
                 ? $CFG_GLPI["proxy_user"] . ":" . (new GLPIKey())->decrypt($CFG_GLPI["proxy_passwd"]) . "@"
                 : "";
             $proxy_string     = "http://{$proxy_creds}" . $CFG_GLPI['proxy_name'] . ":" . $CFG_GLPI['proxy_port'];
-            $options['proxy'] = $proxy_string;
+            $no_proxy = getenv('NO_PROXY');
+            if (!empty($no_proxy)) {
+                $options['proxy'] = [
+                    'http'  => $proxy_string,
+                    'https' => $proxy_string,
+                    'no'    => explode(',', $no_proxy),
+                ];
+            } else {
+                $options['proxy'] = $proxy_string;
+            }
         }
         return new Client($options);
     }
```

If it works for you, you should report the problem to glpi project telling NO_PROXY environment variable is not honored and evenutally share my patch, and this link where there's a note explaining why it is probably not honored: https://docs.guzzlephp.org/en/stable/request-options.html#proxy

**Comment by g-bougard** [comment] 2025-10-02 10:47
Or maybe this patch (didn't try it myself) which transmit targeted agent addresses in "no" "proxy" and make it honored:
```php
diff --git a/src/Agent.php b/src/Agent.php
index 8688f9993a..530c42ad1e 100644
--- a/src/Agent.php
+++ b/src/Agent.php
@@ -701,6 +701,7 @@ class Agent extends CommonDBTM
         foreach ($addresses as $address) {
             $options = [
                 'base_uri'        => $address,
+                'proxy'           => [ 'no' => $this->guessAddresses() ],
             ];
 
             // init guzzle client with base options
diff --git a/src/Toolbox.php b/src/Toolbox.php
index d3d4c0e567..f1d3ab2a12 100644
--- a/src/Toolbox.php
+++ b/src/Toolbox.php
@@ -1337,7 +1337,12 @@ class Toolbox
                 ? $CFG_GLPI["proxy_user"] . ":" . (new GLPIKey())->decrypt($CFG_GLPI["proxy_passwd"]) . "@"
                 : "";
             $proxy_string     = "http://{$proxy_creds}" . $CFG_GLPI['proxy_name'] . ":" . $CFG_GLPI['proxy_port'];
-            $options['proxy'] = $proxy_string;
+            if (!empty($options['proxy']['no'])) {
+                $options['proxy']['http'] = $proxy_string;
+                $options['proxy']['https'] = $proxy_string;
+            } else {
+                $options['proxy'] = $proxy_string;
+            }
         }
         return new Client($options);
     }
```

**Comment by krenaudUR** [comment] 2025-10-02 10:53
> Or maybe this patch (didn't try it myself) which transmit targeted agent addresses in "no" "proxy" and make it honored:
> ```
> diff --git a/src/Agent.php b/src/Agent.php
> index 8688f9993a..530c42ad1e 100644
> --- a/src/Agent.php
> +++ b/src/Agent.php
> @@ -701,6 +701,7 @@ class Agent extends CommonDBTM
>          foreach ($addresses as $address) {
>              $options = [
>                  'base_uri'        => $address,
> +                'proxy'           => [ 'no' => $this->guessAddresses() ],
>              ];
>  
>              // init guzzle client with base options
> diff --git a/src/Toolbox.php b/src/Toolbox.php
> index d3d4c0e567..f1d3ab2a12 100644
> --- a/src/Toolbox.php
> +++ b/src/Toolbox.php
> @@ -1337,7 +1337,12 @@ class Toolbox
>                  ? $CFG_GLPI["proxy_user"] . ":" . (new GLPIKey())->decrypt($CFG_GLPI["proxy_passwd"]) . "@"
>                  : "";
>              $proxy_string     = "http://{$proxy_creds}" . $CFG_GLPI['proxy_name'] . ":" . $CFG_GLPI['proxy_port'];
> -            $options['proxy'] = $proxy_string;
> +            if (!empty($options['proxy']['no'])) {
> +                $options['proxy']['http'] = $proxy_string;
> +                $options['proxy']['https'] = $proxy_string;
> +            } else {
> +                $options['proxy'] = $proxy_string;
> +            }
>          }
>          return new Client($options);
>      }
> ```

This one works (the other one with NO_PROXY doesn't work; NO_PROXY was in my env) @g-bougard

**Comment by orthagh** [comment] 2025-11-24 10:18
The issue will probably be managed by GLPI in a future version.
CF: https://github.com/glpi-project/glpi/pull/22027
