### ISSUE TITLE
Forcing a glpi-agent automatic inventory from GLPI interface doesn't work sometimes

### ISSUE THREAD

**Issue by mightyspiky** [glpi-project/glpi-agent#194] opened 2022-08-09 19:07 UTC
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Forcing a glpi-agent (version 1.4) automatic inventory from GLPI interface (version 10.0.2) doesn't work sometimes. When it happens, I get the following kind of lines in the logs:

```
Aug  9 13:22:42 host glpi-agent[2377]: [http server] unknown path: %E8%E7t%F0%A6B%B1%17%14%D5!$%3E%9B%C8%E7s%8E%18%8D%03%E9%C6o%1F%8CLX%01M%5C%F9%00%3E%13%02%13%03%13%01%C0,%C00%00%9F%CC%A9%CC%A8%CC%AA%C0+%C0/%00%9E%C0$%C0(%00k%C0
```

If I restart glpi-agent and force an automatic inventory again through GLPI interface immediately after that, it works and I don't have the "unknown path" error anymore.

### To reproduce

I don't have the exact steps to reproduce the problem but it seems to happen after many days without having forced an inventory. What is systematic though is that glpi-agent automatic inventory always work when forcing it through GLPI server interface just after having restarted glpi-agent on my client host.

### Expected behavior

Forcing an automatic glpi-agent inventory through GLPI server interface should always work.

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### Additional context

GLPI Agent version: 1.4
GLPI version: 10.0.2
GLPI Inventory plugin: GLPI native inventory from GLPI 10.0.2

**Comment by g-bougard** [comment] 2022-08-10 07:21
Hi @mightyspiky 
do you try to force only one time before restarting the agent ? If no, do you see different "unknown path" for each attempt ?
can you also give few details about your linux operating system and how you installed the agent on it ?

**Comment by mightyspiky** [comment] 2022-08-10 14:27
Here's three tries to force I just did:

```
Aug 10 10:12:21 host glpi-agent[2035]: [http server] unknown path: %D8%DA%11%E3%CD%E8Lr%14%BF.%FD%9C%0Er%94%CC%01%A1%C1*8B%99%E4]%F5%A7Irl%D7%00%3E%13%02%13%03%13%01%C0,%C00%00%9F%CC%A9%CC%A8%CC%AA%C0+%C0/%00%9E%C0$%C0(%00k%C0
Aug 10 10:13:23 host glpi-agent[2035]: [http server] unknown path: %B4%F4%9E!R%B5o%FBfU%D4%115%D4!%08n%EF%BB%221&%99%D8l%22%02%60%F89X%B9%00%3E%13%02%13%03%13%01%C0,%C00%00%9F%CC%A9%CC%A8%CC%AA%C0+%C0/%00%9E%C0$%C0(%00k%C0
Aug 10 10:15:05 host glpi-agent[2035]: [http server] unknown path: %07%F0%A7%F9%19VP%B7%BC%CA%EF%AFy%CCK.&%91%CF%EB%AF%EE%C2%C5%1D%E8n%1E;%E3%9Aj%00%3E%13%02%13%03%13%01%C0,%C00%00%9F%CC%A9%CC%A8%CC%AA%C0+%C0/%00%9E%C0$%C0(%00k%C0
```

It seems the first half of the string is different each time but the second half seems to be the same.

I've installed glpi-agent from the rpm provided on github on a physical host running Oracle Linux 8.6 with UEK R7 kernel (5.15.0). What may be of interest is that the GLPI server is running on a Debian LXC container which is hosted on that physical host so when I reboot that physical host, I guess it would be possible for glpi-agent to start before GLPI server is reachable.

**Comment by g-bougard** [comment] 2022-08-10 15:20
Okay, as you said you don't have the "unknown path" error anymore after the agent is restarted, I can just imagine the listened network status changed between the agent is started and the LXC container is started.

This is not really a glpi-agent issue in my point of view, but a virtual network problem you'll have to figure out. Maybe you can try another virtual network type.

Can I guess the problem happen again if you stop the container, restart the agent and start the container after ?

**Comment by mightyspiky** [comment] 2022-08-10 15:36
The problem appears again as soon as I stop the container, restart the agent on physical host and then restart the container. I know that my setup may be unorthodox but I still see that problem as a bug since it seems GLPI server must be up when the GLPI agents are starting or else they will not fail on startup but they will not operate correctly until their next restart. At least, I think the systemd service of GLPI agent should fail on startup when GLPI server is unreachable.

**Comment by g-bougard** [comment] 2022-08-10 16:25
I'm not totally agree with you. Normally, the agent can start and if the glpi server is down or started later, this won't be a problem.
In your case, the network interface status changes as this is a virtual network interface. This is maybe a bug from the virtual network interface.
You won't have this problem with an agent on another computer.
For LXC containers, there's different possibilities to setup a network interface. You should try another way.
Eventually, you can restart the agent at the end of your booting process from the rc.local file.

**Comment by mightyspiky** [comment] 2022-08-10 16:42
If the agent starts while the server is down, I agree that it won't be a problem for the normal scheduled automatic inventories pushed from the agent to the server but I'm pretty sure it would be a problem when forcing an inventory from GLPI server web interface, even in a case where the agent and the server are on two different physical hosts. I'll try to test that eventually and give feedback here. Thanks for your time.

**Comment by mightyspiky** [comment] 2022-08-10 17:00
I just realized that I can mostly test it right now so that's what I did. I have a physical FreeBSD host with fusioninventory-agent 2.5.2 and I experiment the same problem than with my physical Linux host which contains the GLPI server LXC container. The only thing missing is the "unknown path" error in logs but the steps are the same:

1. Verify that I can force with success an inventory from GLPI server web interface for the specific agent
2. Stop the LXC container which contains the GLPI server
3. Restart the agent (glpi-agent on my Linux box or fusioninventory-agent on my FreeBSD one)
4. Start the LXC container
5. Verify that I can no more force an inventory from GLPI server web interface for the specific agent until its restart

**Comment by g-bougard** [comment] 2022-08-11 08:10
Hi @mightyspiky 

> even in a case where the agent and the server are on two different physical hosts.

I don't think so.

With your FreeBSD scenario, I can just say the problem is probably your network configuration around the server. As I still suggested, you should play with the virtual network configuration on your LXC container for the glpi server.

Anyway I'm closing the issue as I see nothing related with a glpi-agent issue.

**Closed as completed by g-bougard** 2022-08-11 08:10 UTC
Labels: invalid
