### ISSUE TITLE
Network Ports not created for specific Cisco Switches after netinventory

### ISSUE THREAD

**Issue by mpsat** [glpi-project/glpi-agent#469] opened 2023-08-24 08:48 UTC
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

When importing XML generated by "glpi-netinventory.bat", the network ports are not created for some Cisco Switches. The ports are listed in the XML file. It is a device specific bug, as this is only affecting some Cisco models.

You can find two generated inventory files attached.

### To reproduce

Run glpi-netinventory.bat against a Switch
Import generated XML
Check Network ports for generated/updated network device

### Expected behavior

See all network ports inventoried in the XML-File in GLPI

### Operating system

Windows

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI Version 10.0.9 running on Linux, GLPI-Agent 1.5 running on Windows, GLPI-Inventory plugin 1.2.3.

**Comment by mpsat** [comment] 2023-08-24 08:49
[inventory_files.zip](https://github.com/glpi-project/glpi-agent/files/12427489/inventory_files.zip)

networkequipment_0_40.xml is for a Cisco C9300L (Stack)
networkequipment_0_230.xml is for a Cisco C9300 (Stack)

**Comment by g-bougard** [comment] 2023-09-01 15:49
Hi @mpsat 

can you accurately tell which ports you expected to be imported ?

It's possible the one you expect but don't see has a different IFTYPE value that normal ones. In that case, you can edit the related "Netword port types" dropdown entry to authorize its import (See Administration -> Dropdowns -> Networking -> "Netword port types".

**Comment by mpsat** [comment] 2023-09-01 15:55
Only two Ports are shown in GLPI (GI0/0) and BI(0/4). If you compare it against the inventory files, there are lots more interfaces. Maybe in the inventory files for the two listed ports (or the next in the list) is data or a configuration that will cause the import to exit with a failure?

**Comment by g-bougard** [comment] 2023-09-01 16:07
This is a stack switch. When importing the C9300L, I see 3 devices:
![image](https://github.com/glpi-project/glpi-agent/assets/12514489/7f64a874-92cb-4234-b55f-9841071daa1c)

The first has the 2 ports you're talking about and the 2 others have 54 ports each. So your problem description is still far from what we can see. So do you mean "Switch 1" is missing ports ? And so which ones ?

**Comment by raregtp** [comment] 2023-11-01 16:07
I also am seeing this issue, but with a Cisco 3850x stack.  Our stack has 8 switches, with switch 1 being the first switch in the stack as well as being the current management switch.  All switch management is done via VLAN assignment; we're not using the physical management ports.  For switch 1 all we see for network ports is Gi0/0, and then 1 management port called "Management".  When inventory runs, it successfully discovers switch 1 (as it's the current management switch and the only one currently with an IP address), and also discovers switches 2 through 8.  Switches 2 through 8 do show all 56 ports, however we have checked and the ports that should be on switch 1 show up under switch 2, switch 2's ports show up under switch 3, and so on....with the ports that should be on switch 8 just not showing up because all ports show up one switch down the stack as far as GLPI is concerned/showing.

We are currently running GLPI version 10.0.10, GLPI Inventory Plugin 1.3.1, and GLPI agent 1.5-1.  A bit new to uploading logs, so if more info is needed please let me know, happy to help!

**Comment by g-bougard** [comment] 2023-11-02 09:51
Hi @raregtp 
can you share the XML files generated the same way @mpsat shared ? Before sharing, can you test manual import reproduces the same problem you're describing ? The best is to test on a clean GLPI test instance. If you can't, you can remove the devices cleaning them from the trashbin and manually import them.

**Comment by raregtp** [comment] 2023-11-02 14:44
For sure....just pulled the XML last night and looking through it, all the info appears to be there for all 8 switches.  We're still standing up our GLPI instance, so it's fairly clean still, and this switch stack is the only network device we've inventoried so far (we were testing with this stack).  I'll try a manual import of the XML, and no issues sharing but will have to look through and sanitize first.  More to come...

**Comment by raregtp** [comment] 2023-11-02 18:29
Still working on sanitizing, however I did delete the 8 switches in the stack from GLPI.....and there were no other network devices inventoried after that....did the XML import but still see the same results as when the network inventory task runs against this switch stack.

**Comment by g-bougard** [comment] 2023-11-02 18:37
Not sure to understand the problem you're describing. Did you empty the trashbin after deletion ?

**Comment by raregtp** [comment] 2023-11-02 18:37
Yes, I absolutely emptied the trashbin after I deleted the switch stack.

I tried to make the problem description as clear as possible in my first post to the issues.  What part is not clear.....happy to clear it up for you.

**Comment by raregtp** [comment] 2023-11-02 21:05
Ok...this reply promises to be long but I was working with my network engineer and through process of elimination I have very much narrowed down what's causing this.  Buckle-up!

First, attached are two files.  
[itstack - non-working.xml.txt](https://github.com/glpi-project/glpi-agent/files/13244415/itstack.-.non-working.xml.txt)
[itstack - working.xml.txt](https://github.com/glpi-project/glpi-agent/files/13244416/itstack.-.working.xml.txt)

What I've discovered is on our Cisco stack, ports are numbered as follows:

![image](https://github.com/glpi-project/glpi-agent/assets/16689744/75007382-d0bf-43e0-bcdb-9f6a7edb565a)

However, the current management switch in the stack will also have it's physical "management" port exposed as follows:

![image](https://github.com/glpi-project/glpi-agent/assets/16689744/70180382-7195-4cbe-96b4-63d4fce7790b)

If you notice in that pic, the naming of the management port does not follow the same naming as the rest of the ports in the switch.  However, if I modify the XML (the itstack - working.xml is the modified version) and change the name of the management port as follows:

![image](https://github.com/glpi-project/glpi-agent/assets/16689744/af3cba0e-e679-47f6-9f25-56281777ce67)

Then when the XML file is manually loaded into GLPI, the management port _and_ all the production ports show up under Switch 1 in GLPI.  Without this modification to the XML file, the only port that will show up under switch 1 is the management port, with all production switch 1 ports showing up on switch 2, switch 2's production ports showing on switch three, etc. (as I originally described).

I've ran through multiple iterations of this and the above change is the only thing I need to change in the XML to get all ports to show up correctly under their respective switches.  Obviously that's not a solution, but hopefully this will point you to the solution.

Please let me know what questions you have.  Thanks!!

**Comment by g-bougard** [comment] 2023-11-03 08:06
Hi @raregtp 

can you also tell which version of GLPI you're using ?
Anyway, your issue can still probably be fixed by [this #15759 PR](https://github.com/glpi-project/glpi/pull/15759) which should be integrated in GLPI for the next version. Can you try to apply that patch and comment the GLPI PR to help GLPI team to decide its merging ?

@mpsat can you also try to apply that patch on your GLPI ?

**Comment by raregtp** [comment] 2023-11-03 16:02
We are currently running GLPI version 10.0.10, GLPI Inventory Plugin 1.3.1, and GLPI agent 1.5-1.

I'll be trying this over the next hour and will report back.....

**Comment by raregtp** [comment] 2023-11-03 16:31
Looks good!  This does indeed seem to resolve the issue.  Thanks!!

**Comment by g-bougard** [comment] 2023-11-24 16:16
I'm closing this issue as you seem to no more have concern.

Feel free to reopen otherwise.

**Closed as completed by g-bougard** 2023-11-24 16:16 UTC
Labels: bug, Need feedback
