### ISSUE TITLE
Conflict of computers with the same name and different entities

### ISSUE THREAD

**Issue by Claonilton** [glpi-project/glpi-agent#124] opened 2022-05-20 02:37 UTC
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Entity 1 and Entity 2

In Entity 1 I have a station named: PC01 and it is synchronized.

If in Entity 2 I have a PC01 and I try to synchronize an error occurs.

### To reproduce

If the hostname of the machine already exists in GLPI, when trying to synchronize the system presents the following error:
[Thu May 19 21:41:53 2022][error] [http client] internal response: 500 read timeout

If the hostname on the station is renamed and we force sync after restarting the machine. Synchronization is performed.

The new sync instead of creating a new station, called: pc01_rename changed the station from entity01 to pc01 entity02

### Expected behavior

Both in Entity 01 and room in Entity 02 we have two computers: pc01 and pc01.
Entity01-pc01
and
Entity02-pc01

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

10.0.0

**Comment by g-bougard** [comment] 2022-05-20 07:56
Hi @Claonilton 
again this should be a server-side problem or at least partially.
Before transferring to GLPI server team, I would like to clarify a point: the renamed computer is not created but the one with original name is moved from first entity to second one. Can you clarify if the 2 computers are sharing something ? Are they virtual machine cloned for example ?

Anyway can you share the output of the following command run on first computer, the one you want to see in entity01:
```
glpi-inventory --partial bios --tag entity01
```

Then can you share the output of the following command run on the second computer, the one you want to see in entity02:
```
glpi-inventory --partial bios --tag entity02
```

**Comment by Claonilton** [comment] 2022-05-27 11:12
First:
 ![image](https://user-images.githubusercontent.com/16517344/170249511-029fee68-bfed-45cb-9670-306f4b6747a7.png)
![image](https://user-images.githubusercontent.com/16517344/170249780-470dcb0d-b867-40cd-99e5-9bc3a3c267a8.png)

second:
![image](https://user-images.githubusercontent.com/16517344/170252810-dfb2e15b-b04d-46ee-b1ed-34634c33484b.png)

**Comment by g-bougard** [comment] 2022-05-27 12:41
Hi @Claonilton 
one weird thing is the 2 computers seems differents from the Bios point of view, but they also seem to be "Physical" devices with exactly the same UUID but without Bios serial number. This explains there's a conflict as GLPI will just use the UUID to match the computer.
I don't understand also why the UUID seems weird too: it seems to be composed of incremented long integers starting from 0x0002.
Can you explain how the 2 computers has been installed to have such same UUID ? Were they installed using a cloned OS or something like this ?

Actually, I can confirm you this is not a GLPI Agent bug as from it's point of view the same computer seems to be uniquely identified. Of course, as human, we can see they are differents, but following the standard import rules, they seems to be the same computer and this should not happen. I really think your problem is around how the system UUID is created.

**Comment by g-bougard** [comment] 2022-05-27 13:47
Quickly searching for the 03000200-0400-0500-0006-000700080009 UUID on internet gives me the feeling you're facing a poor motherboard design problem. I'm not sure, but maybe you should just check your motherboards manufacturers for BIOS update fixing this problem.

If you want to quickly fix the problem in GLPI, just make sure the 2 computers have a different name.

Anyway the agent can't do more than what the hardware is showing.make a trick 

Maybe you can make a trick with "additional-content" configuration:
1. create a file which will replace the UUID in inventory
2. configure "additional-content" to load that file

Actually this is not an easy way and I should fix this code as when using json format it doesn't work exactly the same way than using XML format. Here is how you can generate an additional content as json for the current version (this will probably change in the next version):
1. create a partial inventory for hardware category: `glpi-inventory --partial hardware >hardware.json`
2. edit hardware.json to:
   2.1. rename "hardware" to "HARDWARE" under the "content" section
   2.2. rename all properties under "HARDWARE" with the uppercase equivalent. For instance, "uuid" must be replaced by "UUID".
   2.3. update any value you need to fix: here only UUID should be changed to something convenient (unique in your network)
3. in registry, set "additional-content" configuration with the full path to your "hardware.json" file.

When using json format, all the hardware section will be replaced by the uppercase one found in the file. This is what I want to change in next version. In your case, you may want to change UUID, but NAME also.

**Comment by g-bougard** [comment] 2022-06-07 06:18
Closing without feedback.
Feel free to reopen or just comment.

**Closed as completed by g-bougard** 2022-06-07 06:18 UTC
Labels: help wanted
