### ISSUE TITLE
GLPI Agent - Inventory DNS_DOMAIN & FQDN bug

### ISSUE THREAD

**Issue by mpsrx** [glpi-project/glpi-agent#795] opened 2024-10-17 13:02 UTC
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Hello, I have an issue with the glpi agent because during the system inventory, it displayed an incorrect DNS_DOMAIN and FQDN. The server is named `ww999.somedomain.pl`, but in the agent's inventory file, it shows DNS_DOMAIN as `somedomain.pl.somedomain.pl` and in the FQDN field, it shows `ww999.somedomain.pl.somedomain.pl` and on other machine it shows `server.otherdomain.pl.somedomain.pl`.

Agent version: 
GLPI Agent (1.11-1)
Source time: 2024-09-24 09:34
Installed from: https://github.com/glpi-project/glpi-agent/releases/download/1.11/glpi-agent-1.11-linux-installer.pl

Output from glpi-inventory
```
    <OPERATINGSYSTEM>
      <ARCH>x86_64</ARCH>
      <BOOT_TIME>2024-09-14 10:43:14</BOOT_TIME>
      <DNS_DOMAIN>somedomain.pl.somedomain.pl</DNS_DOMAIN>
      <FQDN>ww999.somedomain.pl.somedomain.pl</FQDN>
      <FULL_NAME>Debian GNU/Linux 12 (bookworm)</FULL_NAME>
      <HOSTID>4f4dc5fa</HOSTID>
      <INSTALL_DATE>2024-08-20 09:55:38</INSTALL_DATE>
      <KERNEL_NAME>linux</KERNEL_NAME>
      <KERNEL_VERSION>6.1.0-23-amd64</KERNEL_VERSION>
      <NAME>Debian GNU/Linux</NAME>
      <SSH_KEY>removed</SSH_KEY>
      <TIMEZONE>
        <NAME>Europe/Warsaw</NAME>
        <OFFSET>+0200</OFFSET>
      </TIMEZONE>
      <VERSION>12.6</VERSION>
    </OPERATINGSYSTEM>
```

hostname:
```w
w999.somedomain.pl
```

hostname -d:
```
somedomain.pl
```

hostnamectl:
```
 Static hostname: ww999.somedomain.pl
       Icon name: computer-vm
         Chassis: vm 🖴
      Machine ID: -removed-
         Boot ID: -removed-
  Virtualization: kvm
Operating System: Debian GNU/Linux 12 (bookworm)
          Kernel: Linux 6.1.0-23-amd64
    Architecture: x86-64
 Hardware Vendor: QEMU
  Hardware Model: Standard PC _i440FX + PIIX, 1996_
Firmware Version: rel-1.16.0-0-gd239552ce722-prebuilt.qemu.org
```

### To reproduce

1. Install GLPI Agent using https://github.com/glpi-project/glpi-agent/releases/download/1.11/glpi-agent-1.11-linux-installer.pl
2. Run glpi-inventory

### Expected behavior

The expected behavior is that the DNS_DOMAIN should be `somedomain.pl`, and the FQDN should be `ww999.somedomain.pl`.

### Operating system

Linux

### GLPI Agent version

v1.11

### GLPI version

10.0.16

### GLPIInventory plugin or other plugin version

Not applicable

**Comment by g-bougard** [comment] 2024-10-17 14:07
Hi @mpsrx 

as I can see, this problem concerns a vm which is probably based on a template or cloned from another vm where agent was still installed... and where it has still been run.

Your problem is the first time glpi-agent run, it stored a `deviceid`. On linux, this `deviceid` is found in `/var/lib/glpi-agent/GLPI-Agent.dump`. For a VM template, you should remove this file before using it or cloning from it. Or you can remove it during the provisioning.

Of course, you can remove it at any time and restart the service: the next time tasks will be run a new `deviceid` will be generated based on the current host.

**Comment by mpsrx** [comment] 2024-10-17 14:17
Hi @g-bougard, I installed the agent cleanly from the installation script on a VM.

**Comment by mpsrx** [comment] 2024-10-17 14:22
File: GLPI-Agent.dump
  Size: 92              Blocks: 8          IO Block: 4096   regular file
Device: 8,18    Inode: 525082      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-10-17 16:13:06.018791657 +0200
Modify: 2024-10-17 14:03:07.454168876 +0200
Change: 2024-10-17 14:03:07.454168876 +0200
 Birth: 2024-10-17 11:31:48.234563557 +0200

**Comment by g-bougard** [comment] 2024-10-17 14:29
Well, sorry, it seems I read too quickly your issue.

**Comment by g-bougard** [comment] 2024-10-18 08:40
Hi @mpsrx 

can you share the output of the following command on the involved computer ?
```
perl -MNet::Domain -e 'print Net::Domain::hostfqdn(), " ; ", Net::Domain::hostdomain(), "\n"'
```

Indeed, for FQDN & DOMAIN_NAME, glpi-agent just use the output of the Net::Domain library. So maybe something is wrong for that library, or maybe something is wrong with Debian 12, or maybe the way the hostname is setup on this computer is not correct.

**Comment by mpsrx** [comment] 2024-10-18 08:48
Hi @g-bougard 
`ww999.somedomain.pl.somedomain.pl ; somedomain.pl.somedomain.pl`

**Comment by g-bougard** [comment] 2024-10-18 08:57
Can you share the output of these commands:
```
hostname
hostname -f
hostname -d
hostname -A
```

**Comment by mpsrx** [comment] 2024-10-18 09:02
hostname
`ww999.somedomain.pl`

hostname -f
`s999.somedomain.pl`

hostname -d
`somedomain.pl`

hostname -A

**Comment by g-bougard** [comment] 2024-10-18 09:12
Just tested on a debian 12 VM:
```
gbougard@debian-12:~$ sudo hostname debian-12.domain.org
gbougard@debian-12:~$ hostname
debian-12.domain.org
gbougard@debian-12:~$ hostname -f
debian-12.domain.org
gbougard@debian-12:~$ hostname -d
domain.org
gbougard@debian-12:~$ hostname -A
debian-12.domain.org debian-12.domain.org 
gbougard@debian-12:~$ perl -MNet::Domain -e 'print Net::Domain::hostfqdn(), " ; ", Net::Domain::hostdomain(), "\n"'
debian-12.domain.org.fr ; domain.org.fr
```

Something seems really wrong with Net::Domain library.

But in your `hostname` outputs, `hostname` one is really different than `hostname -f` one. I'm really curious to know how you setup the hostname on this computer.

**Comment by g-bougard** [comment] 2024-10-18 09:18
Digging in Net::Domain library, have you something interesting in the output of this command ?
```
perl -MNet::Config -MData::Dumper -e 'print Dumper(\%NetConfig)'
```

**Comment by g-bougard** [comment] 2024-10-18 09:20
Output of following commands can be also interesting:
```
uname -n
perl -MNet::Config -e 'print $INC{"Net/Config.pm"}, "\n"'
```

**Comment by mpsrx** [comment] 2024-10-18 09:24
> Digging in Net::Domain library, have you something interesting in the output of this command ?
> 
> ```
> perl -MNet::Config -MData::Dumper -e 'print Dumper(\%NetConfig)'
> ```

perl -MNet::Config -MData::Dumper -e 'print Dumper(\%NetConfig)'
```
$VAR1 = {
          'inet_domain' => undef,
          'ftp_ext_passive' => 0,
          'ph_hosts' => [],
          'test_hosts' => 1,
          'snpp_hosts' => [],
          'test_exist' => 1,
          'ftp_firewall' => '',
          'ftp_int_passive' => 0,
          'local_netmask' => '',
          'pop3_hosts' => [],
          'time_hosts' => [],
          'ftp_firewall_type' => '',
          'smtp_hosts' => [],
          'daytime_hosts' => [],
          'nntp_hosts' => []
        };

```





> Output of following commands can be also interesting:
> 
> ```
> uname -n
> perl -MNet::Config -e 'print $INC{"Net/Config.pm"}, "\n"'
> ```

uname -n
`ww999.somedomain.pl`

perl -MNet::Config -e 'print $INC{"Net/Config.pm"}, "\n"'
`/usr/share/perl/5.36/Net/Config.pm`

**Comment by g-bougard** [comment] 2024-10-18 09:30
Okay, Net::Config is correct.

Have you lines for domain searching in `/etc/resolv.conf` ? I mean any line starting with `search` keyword.

And finally have you any entry in `/etc/hosts` file related to ip starting by `127.0.` which can contain reported hostname or domain ?

I'm still interested to know how hostname has been set on your computer.

**Comment by mpsrx** [comment] 2024-10-18 09:50
I don't know how the hostname was set; I wasn't the one who set it and i checked resolv.conf, but there's nothing about 'search,' only nameserver entries. 
In /etc/hosts, I don't see the hostname 'ww999' set.

**Comment by g-bougard** [comment] 2024-10-18 10:11
Have you something different than `ww999.somedomain.pl` in `/etc/hostname` ?

Does this computer was upgraded from a previous Debian version ?

My problem here is I can't reproduce, so my guess for now is you have an exotic/weird configuration which put Net::Domain library in trouble.
And to me this is just not normal `hostname` & `hostname -f` don't give the same hostname in your case.

**Comment by mpsrx** [comment] 2024-10-18 10:22
cat /etc/hostname
`ww999.somedomain.pl`

Yes, it was upgraded from an older debian version

**Comment by g-bougard** [comment] 2024-10-18 10:52
So maybe some old scripts are mixing the way hostname is set during computer start up.

As you said `hostname -f` is reporting `s999.somedomain.pl` where `hostname` is reporting `ww999.somedomain.pl`, can you search where this can be set on the system ? Maybe a simple `grep -r "s999" /etc` will help.

**Comment by mpsrx** [comment] 2024-10-18 11:07
I don't see any files matching 's999' in grep, except for Apache2 configuration files.

**Comment by g-bougard** [comment] 2024-10-18 12:18
Does this mean the host has an ip for which reverse dns is `s999.somedomain.pl` ?

If yes, real hostname should probably be `s999.somedomain.pl` and not `ww999.somedomain.pl` or reverse dns should be `ww999.somedomain.pl`.

**Comment by mpsrx** [comment] 2024-10-18 12:37
Reverse DNS is set to ww999.somedomain.pl.

**Comment by g-bougard** [comment] 2024-10-18 14:17
While testing I had a situation where I reproduced the domain name duplication with Net::Domain, but it was reset automatically by systemd-hostnamed service. Anyway this gave me few clues.

I finally understood a point: at some time, Net::Domain tries to resolv hostname after a concatenation of each part of hostname and domainname.

I got a case when if I set hostname with `sudo hostnamectl hostname debian-12.domain.org` I got `debian-12.domain.org.domain.org` as this dns name is resolved to a real IP... Translated to your case, this probably means `ww999.somedomain.pl.somedomain.pl` is resolved to an ip when DNS resolution is made from your computer. Check `host ww999.somedomain.pl.somedomain.pl` to verify.

I was able to fix this issue by putting this line in `/etc/hosts`:
```
127.0.1.1	debian-12.domain.org	debian-12
```
And run the following command:
```
sudo hostnamectl debian-12
```

But if you own the `somedomain.pl` domain, maybe you can first check if `ww999.somedomain.pl.somedomain.pl` is resolved and if yes, fix it as it should probably not. If `ww999.somedomain.pl.somedomain.pl` is resolved to a local ip due to the computer dns resolution configuration, this is firstly a local system configuration problem.

To me, this weird domain that glpi-agent reports is finally a symptom of dns name resolution problem.

**Comment by mpsrx** [comment] 2024-10-21 10:15
Is there any way to override these fields from the agent's configuration? This solution doesn't help me, as the server fleet could be configured with strange hostnames.

**Comment by g-bougard** [comment] 2024-10-30 14:56
Hi @mpsrx 

if you have ww999.somedomain.pl.somedomain.pl really resolved, this is more than strange. Maybe you should change the domain usage policy. This is up to you.

I agree there's a bug, but as I show you the bug is more in Net::Domain library. You may want to contact its maintainer. But I'm not sure a bug triggered by a strange domain usage is valid.

Here with GLPI-Agent, you don't have any configuration to change how DNS_DOMAIN & FQDN will be reported. You can only modify the code to cleanup values as you want.

But we won't handle this case ourselves, this should be done in Net::Domain or fixed by changing dns domain management.

**Closed as completed by g-bougard** 2024-10-30 14:56 UTC
Labels: help wanted, invalid

**Comment by Orabig** [comment] 2025-01-02 09:09
For information : we had the same issue, and the solution was simple :

We were in the same situation than @mpsrx , and the symptom was that the `hostname` was unable to correctly guess the domain name of the host : 

```
$ hostname -f
hostname: Name or service not known
```

**The solution** was to fix `/etc/hosts` file so that it defines the full qualified domain name of the server : 

```
127.0.0.1   <fqdn> <hostname> localhost
```

For example

```
127.0.0.1   server01.domain.com   server01   localhost
```

Just by fixing this, the issue is resolved, both with `hostname` system commands and GLPI Agent

```
$ hostname -f
server01.domain.com
```
