### ISSUE TITLE
GLPI-Agent 1.10 windows - devices connections

### ISSUE THREAD

**Issue by Aekinox** [glpi-project/glpi-agent#741] opened 2024-08-21 10:27 UTC
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

glpi-agent 1.10 does not disconnect devices that are not present on computer

### To reproduce

1. connect an external screen
2. force inventory from `http://localhost:62354/`
3. disconnect external screen
4. force inventory from `http://localhost:62354/`
5. external screen stay in computer's connexions

### Expected behavior

remove connexion 

### Operating system

Windows

### GLPI Agent version

v1.10

### GLPI version

10.0.14

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

**Comment by g-bougard** [comment] 2024-08-26 07:05
Hi @Aekinox 

this seems not a glpi-agent issue but a server issue. Please try first to upgrade your glpi server as there're some fixes related to such comportment in latest release.

If the problem is persisting, you can report the [issue on glpi project](https://github.com/glpi-project/glpi/issues) and disable [full-inventory-postpone](https://glpi-agent.readthedocs.io/en/latest/configuration.html#full-inventory-postpone) by setting it to `0` until the problem is fixed in GLPI.

**Closed as completed by g-bougard** 2024-08-26 07:05 UTC
Labels: bug, server issue
