### ISSUE TITLE
glpi esx use of uninitialized value in unpack

### ISSUE THREAD

**Issue by mareban** [glpi-project/glpi-agent#506] opened 2023-10-02 14:10 UTC
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Hello,

We've the latest GLPI and glpi-agent nightly build and still cannot have an inventory of  our virtual VMware infrastructure form Vsphere :-( !

Running the glpi-esx or form a task scheduling, we still have this error message : 

Use of uninitialized value in unpack at /usr/share/glpi-agent/lib/GLPI/Agent/SOAP/VMware/Host.pm line 384.
'x' outside of string in unpack at /usr/share/glpi-agent/lib/GLPI/Agent/SOAP/VMware/Host.pm line 384.

 We've try to use no-compression parameter and still have the issue !

Is it a known bug , or what can we do to have an esx inventory (maybe missing perl dependancies or a limit somewhere ) ?

Thanks for your help  

PS : error happens when unpack esx serial number !

### To reproduce

run glpi esx or vmware invotory task

### Expected behavior

working esx inventory 

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.9

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context

last nightly build

**Comment by g-bougard** [comment] 2023-10-02 16:15
Hi @mareban 

I'm not aware of such a problem.

Anyway, it may be fixed in another branch I'm working on since a while, but I'm really not sure.

So can you try to replace the 2 following files in your installed lib ?
 - [lib/GLPI/Agent/SOAP/VMware/Host.pm](https://raw.githubusercontent.com/glpi-project/glpi-agent/2e7fa516e8e7a0efeab68afacbf6743945c75798/lib/GLPI/Agent/SOAP/VMware/Host.pm)
 - [lib/GLPI/Agent/SOAP/VMware.pm](https://raw.githubusercontent.com/glpi-project/glpi-agent/2e7fa516e8e7a0efeab68afacbf6743945c75798/lib/GLPI/Agent/SOAP/VMware.pm)

If that doesn't fix the problem, I'll ask you to share the `*-hostfullinfo.dump` file you can try to generate using the `--dump` option with [glpi-esx](https://glpi-agent.readthedocs.io/en/latest/man/glpi-esx.html) command. You can put the file in a zip and send me the archive to `gbougard <at> teclib <dot> com`. The idea is to keep it private. I should be able to reproduce the problem with the dump. And you can even first try yourself to reproduce using the `--dumpfile` [glpi-esx](https://glpi-agent.readthedocs.io/en/latest/man/glpi-esx.html) option: you don't need to set `--host`, `--user` & `--password` that way if I remember well.

**Comment by mareban** [comment] 2023-10-03 14:03
Hi , 

Thanks for your help ! Nope :-( 

What permissions are needed by an AD account to scan inventory from vsphere ?


Thanks for you help

**Comment by g-bougard** [comment] 2023-10-03 16:56
Indeed, it seems you esx computer doesn't report any uuid. Glpi agent needs it to create a serial for your computer, but GLPI needs it to import the computer.
I can fix the error, but this will mean nor uuid nor serialnumber will set in inventory and so GLPI won't import it.

We probably can't fix your uuid missing problem in glpi-agent unless something changed with your ESX server version. So what's your ESX system version ?
Anyway, you should first check why your computer doesn't report an uuid.

About permissions, I can't tell you, I'm not an ESX expert. I can just tell you the agent uses SOAP API, so the user should have the permission to call SOAP API.

**Comment by g-bougard** [comment] 2023-10-03 16:59
Humpf, indeed, the uuid is missing on a VM, not on the ESX host itself. You should check if a VM is missing an UUID and if you can set it.

**Comment by g-bougard** [comment] 2023-10-03 17:19
Can you try this [lib/GLPI/Agent/SOAP/VMware/Host.pm](https://github.com/glpi-project/glpi-agent/blob/f9bbdde455842d31a0edf6d4ef067b4ce58c963c/lib/GLPI/Agent/SOAP/VMware/Host.pm) file ?
It should at least fix your error problem. But you'll still have a VM that won't be imported in GLPI.

**Comment by mareban** [comment] 2023-10-03 20:49
Hello,

Now we can have an nice inventory of our virtual environment :-) !

Thanks a lot for your support and the quick fix, we always appreciate your help.

BR

**Comment by g-bougard** [comment] 2023-10-04 08:29
Hi @mareban 

thank you for your feedback.

For your information, I included this fix in f9bbdde455842d31a0edf6d4ef067b4ce58c963c which is in a dedicated branch for the glpi-netscan feature. This means the fix won't be available in nightly build until I merge this branch. I think the merge could occur in a week or 2, and the next public release will occur soon after.

**Closed as completed by g-bougard** 2023-10-04 08:29 UTC
Labels: bug
