### ISSUE TITLE
Missing GLPI-AgentMonitor and sysstray with Agent release 1.6.1

### ISSUE THREAD

**Issue by giudig** [glpi-project/glpi-agent#534] opened 2023-11-21 11:15 UTC
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Tested on Window 10 22H2, Windows Server 2019 Standard, Windows Server 2022 Standard
After upgrade to 1.6.1 release or with a clean setup the GLPI-AgentMonitor and sysstray is missing.

### To reproduce

1. Install the agent selecting "Install GLPI-AgentMonitor as systray icon for all users"

### Expected behavior

GLPI-AgentMonitor should be available as systray as reported [here](https://glpi-agent.readthedocs.io/en/latest/installation/index.html#glpi-agent-monitor) 

### Operating system

Windows

### GLPI Agent version

1.6.1

### GLPI version

10.0.10

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.3.3

**Comment by g-bougard** [comment] 2023-11-23 09:29
Hi @giudig 

during update, the installer needs to stop the GLPI-AgentMonitor systray process. But as we are not in the user session (as the installer switches in an administrator session), we are not able to restart the process ourself. You have to disconnect and reconnect your user session to have the systray icon restarted as we use a system feature.

Or do you mean even when restarting the user session GLPI-AgentMonitor is no more started after an update ?

**Comment by g-bougard** [comment] 2023-11-23 09:50
Also you should always have a "GLPI Agent Monitor" entry in the start menu to restart manually the systray icon.

**Comment by lexcorp** [comment] 2023-11-27 21:30
Same here, I have the same detail, I have version 1.5 installed, I updated to version 1.6.1 and the shortcut does not appear in the start menu, nor do I see the icon in the system tray.

**Comment by g-bougard** [comment] 2023-11-28 08:08
Hi @lexcorp 

this is not exactly the details: you're speaking about shortcuts missing in start menu where @giudig did not.

Can you share an export of the following registry key ?
```
HKEY_LOCAL_MACHINE\SOFTWARE\GLPI-Agent\Installer
```

**Comment by lexcorp** [comment] 2023-11-28 21:37
This is the registry file:

[glpi-agent-installer.zip](https://github.com/glpi-project/glpi-agent/files/13493365/glpi-agent-installer.zip)

![image](https://github.com/glpi-project/glpi-agent/assets/5751288/b08d0178-5e1f-4f33-bffc-02af8a0cbcf1)

**Comment by g-bougard** [comment] 2023-11-29 16:20
Hi @lexcorp 

As AgentMonitor is set to `0` in registry it tells you didn't install glpi-agent with Glpi-AgentMonitor, so it's normal to not have the start menu entry. How did you installed the agent ?

**Comment by giudig** [comment] 2023-11-29 17:31
Hello @g-bougard,

as described in the bug section, GLPI-AgentMonitor is missing after upgrade to 1.6.1 release but also uninstalling it and installing again it with a clean setup and selecting "Install GLPI-AgentMonitor as systray icon for all users" during setup wizard.
I also disconnected and reconnect my user.
GLPI-AgentMonitor.exe is missing in C:\Program Files\GLPI-Agent\perl\bin and no entry is available in the start menu.
Here is my registry key export:
![image](https://github.com/glpi-project/glpi-agent/assets/47992054/838e9302-2712-423a-a00c-71b50e5ad0fb)

I tried again on a Windows 11 test client machine selecting "Install GLPI-AgentMonitor as systray icon for all users" with a clean installation and also in this case I found again the same bug.
I also disconnected and reconnect my user but again GLPI-AgentMonitor.exe is missing in C:\Program Files\GLPI-Agent\perl\bin and no entry is available in the start menu.
Here is the registry key export:
![image](https://github.com/glpi-project/glpi-agent/assets/47992054/819438aa-75b2-490b-9541-d0ca6c9949a6)

AgentMonitor registry key in this case is 0, but I'm sure I selected "Install GLPI-AgentMonitor as systray icon for all users"  during setup wizard.

**Comment by lexcorp** [comment] 2023-11-29 17:43
Hi @g-bougard, I have selected checkbox "Install GLPI-AgentMonitor as systray icon for all users"

![image](https://github.com/glpi-project/glpi-agent/assets/5751288/4ecce897-4619-4430-9322-01b49d2a5448)

**Comment by g-bougard** [comment] 2023-11-30 17:07
Hi,

I take a long time today to investigate. I wasn't able to reproduce the problem for Glpi-AgentMonitor, but I found an issue with other configuration values depending on some obscure windows reason. So probably the problem is essentially random and only affect few installer properties. For you, maybe the installer fails to setup AGENTMONITOR MSI property as desired and this results by not installing GLPI-AgentMonitor.

Then after a MSI setup deep review, I think we may have an issue in MSI Actions sequence computing: I suspect some setup actions are not run in the right order. I just pushed an update which try to avoid such kind of issue. So can you please try the next nightly build and tell me if it seems to fix your issue ?
Or you may look at the GH Actions development build an extract the MSI installer from the Windows-Build artifact from there: https://github.com/glpi-project/glpi-agent/actions/runs/7049146927

**Comment by jerric12** [comment] 2023-12-07 13:33
Hi,
I've the same problem. I updated to 1.6.1 and the systray icon doesn't appear.
AgentMonitor registry key is 0, even if I selected "Install GLPI-AgentMonitor as systray icon for all users" during setup wizard.
I checked manually this key et the result is the same. No systray icon.
Thank you for all the work done for this plugin 😉

**Comment by g-bougard** [comment] 2023-12-07 14:20
Hi there,

can you test [latest nightly build](https://nightly.glpi-project.org/glpi-agent/) to check if this problem is fixed by the update I made last week ?

If it's fixed, I'll probably release a new version next week.

**Comment by giudig** [comment] 2023-12-07 14:32
Hello @g-bougard,
I did a test with the latest nightly build and I can confirm that with this release the issue is solved and the GLPI-AgentMonitor is available.
Waiting for the new version....Many thanks for all the work done!
![image](https://github.com/glpi-project/glpi-agent/assets/47992054/7f13648b-3e59-4574-88b0-bb9453f9144a)

**Comment by jerric12** [comment] 2023-12-07 14:34
> Hi there,
> 
> can you test [latest nightly build](https://nightly.glpi-project.org/glpi-agent/) to check if this problem is fixed by the update I made last week ?
> 
> If it's fixed, I'll probably release a new version next week.

Hi, well done, it' perfect. Thanks a lot

**Comment by g-bougard** [comment] 2023-12-07 14:38
Thank you for the feedback.

So I can close it.

**Closed as completed by g-bougard** 2023-12-07 14:38 UTC
Labels: bug, Need feedback
