### ISSUE TITLE
The creator of the ticket does not become the requester in GLPI v10

### ISSUE THREAD

**Issue by nordes85** [glpi-project/glpi-agent#106] opened 2022-04-28 14:31 UTC
Any user who enters a ticket is not reported as a requestor in the ticket using the simplified interface.
You can't even add the "requester" field as a field in the simplified interface.

For admins, the requesting field is empty, and you are forced to look at the ticket creator.

![1](https://user-images.githubusercontent.com/76699265/165775943-255d3836-2754-49dd-bce2-8ba827ddb2e2.png)
![2](https://user-images.githubusercontent.com/76699265/165776042-8336074a-b426-4292-8cdb-71e6c226fe7f.png)

**Comment by orthagh** [comment] 2022-04-28 14:33
You open the issue in the wrong repository. Here it's for the inventory agent.

By the way, see fix already done : https://github.com/glpi-project/glpi/pull/11328 (or take current nightly : https://nightly.glpi-project.org/glpi/)

duplicate of https://github.com/glpi-project/glpi/issues/11334, and https://github.com/glpi-project/glpi/issues/11377

**Closed as completed by orthagh** 2022-04-28 14:33 UTC
