### ISSUE TITLE
Inventory: The type of network adapter for Ethernet is not added. 

### ISSUE THREAD

**Issue by sonntagausgang** [glpi-project/glpi-agent#100] opened 2022-04-21 15:18 UTC
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

The type of network adapter for Ethernet is not added. Because of this, glpi10 cannot correctly display the MAC address of the network adapter.
This happens both when taking inventory via glpi-agent over the network and through glpi-inventory when taking inventory in a json file.

### To reproduce

1. I download the agent to my computer
2. Running glpi-agent --server http://address or glpi-agent --json > inventory.json
3. Waiting for the inventory to finish on the computer or downloading a json file.

### Expected behavior

I expect to see the imported mac address in the network ports for the network adapter.
But he is missing.
This does not always happen. Sometimes it works correctly and the mac address is imported.

### Operating system

Windows, Linux

### GLPI Agent version

1.2

### GLPI version

10.0.0-rc3

### Additional context

By comparing the working and non-working json file, it was found that the agent does not always add the line: "type": "ethernet" to the network adapter.
Because of this, the MAC address of the computer is not imported into glpi 10.

**Comment by g-bougard** [comment] 2022-05-02 12:21
Hi @sonntagausgang 

can you report the output of `glpi-inventory --debug --debug --partial network` from all computers having such a problem ?

Also you're telling the agent not always add the line `"type": "ethernet"`, but can you tell if this happens on one computer, meaning on one computer it doesn't always add the line or do you mean it appears on some computers and not on others, but all the time ?

I need to understand if the problem is specific to some computer configuration the agent doesn't support for now or if this is another problem. For example, on windows, this still can be a computer problem having WMI not responding in time and in that case, just updating `backend-collect-timeout` value can fix the problem.

**Comment by g-bougard** [comment] 2022-05-19 14:14
Hi @sonntagausgang 
I'm closing the issue without any answer to my questions.
Feel free to reopen.

**Closed as completed by g-bougard** 2022-05-19 14:14 UTC
Labels: bug, question
