### ISSUE TITLE
LLDP discovery issue with Juniper devices

### ISSUE THREAD

**Issue by liedekef** [glpi-project/glpi-agent#331] opened 2023-02-02 14:22 UTC
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

LLDP of Juniper SRX not correctly interpreted/matched to an existing SNMP discovered device, causing continous creations of unmanaged devices.

### To reproduce

1) do a SNMP discovery of a juniper SRX and a QFX network device
2) both arrive fine in the network devices
3) both have LLDP activated
4) do a network inventory task
 - on the SRX a port ge-0/0/10 with portnumber 591 exists, correctly discovered in the GLPI network devices
 - on the QFX, via test snmp the LLDP info is reported as:

iso.0.8802.1.1.2.1.4.1.1.7.20715326.540.87 = STRING: "591"
iso.0.8802.1.1.2.1.4.1.1.8.20715326.540.87 = STRING: "ge-0/0/10.0"

==> the ".0" already causes problems, so a new unmanaged device gets created :
![image](https://user-images.githubusercontent.com/75667/216348021-11a88d05-0df0-4612-8523-46db4d82872a.png)

So there I see 2 problems: the ".0" should somehow get removed and the portnumber of the new configured device is 0 (which is wrong, in the generated discovered XML it is correctly set as 591 in IFNUMBER).
Even when I change Hardware.pm to remove the ".0" (in _getLLDPInfo) , the problem with the wrong port always causes a new unmanaged device to be created based on the mac+ifnumber rule:
![image](https://user-images.githubusercontent.com/75667/216348651-ed6e6912-981f-463b-8384-b23930152bc6.png)

### Expected behavior

the LLDP discovered info should point to the existing device/port, not a new unmanaged one.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by g-bougard** [comment] 2023-02-02 14:34
Hi @liedekef 
can you test current nightly as new fixes has been applied on LLDP support ? Like 7478ec4
If this doesn't fix your problem, can you share the XML inventories of the 2 devices ? And maybe we will need a [full snmpwalk output](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output) of the problematic device.

**Comment by liedekef** [comment] 2023-02-03 08:53
I already tried with just Hardware.pm, but that didn't change anything. I'm now retrying with the nightly build.
One thing that comes up after discovery:
![image](https://user-images.githubusercontent.com/75667/216554829-8fe5fc7d-288e-4826-8dae-b275650ae3c5.png)
==> the network ports start with 128.0.0.1 (internal ip), but once I run the inventory the first IP is taken for snmp, which doesn't work of course. SO I always need to change the IP info of the switch so the first IP is our "real" management ip (otherwise snmp doesn't work). Maybe there is a better method for this?

Other test ongoing now ...

**Comment by liedekef** [comment] 2023-02-03 09:07
It seems less is being inventorised now.
After initial discovery: a network device "testlab-srx" is created (but it seems to contain less info than before), together with extra devices.
After the inventory-run, extra unmanaged devices "testlab-srx" are created, one per LLDP port seen on the other switch (but with wrong number).
If you need more info: tell me the command(s) to run and where to put the resulting files :-)

**Comment by g-bougard** [comment] 2023-02-03 09:47
The management port with 8 ips is a really problem and a colleague is still working on it. You'll have to wait next GLPI 10.0.7 release for that problem.
Actually, you should probably generate manually the XML inventory with [glpi-netinventory](https://glpi-agent.readthedocs.io/en/latest/man/glpi-netinventory.html) script from nightly build.
Then try to import the XML manually using `glpi-injector` or from the GLPI UI, in "Inventory" Administration, "Import from file" page. If there's still problem with post, please share the XMLs so we can investigate.

**Comment by liedekef** [comment] 2023-02-03 10:45
I tried manually, but it didn't make a difference. I then went in Hardware.pm and saw this code:

```
        # portId is either a port number or a port mac address,
        # duplicating chassisId
        my $portId = $lldpRemPortId->{$suffix};
        if ($portId !~ /^0x/ or length($portId) != 14) {
            $portId = getCanonicalString($portId);
            if ($portId =~ /^\d+$/) {
                $connection->{IFNUMBER} = $portId;
            } else {
                my $maybe_mac = lc(alt2canonical($portId));
                if ($maybe_mac) {
                    push @{$connection->{MAC}}, $maybe_mac;
                } else {
                    $connection->{IFDESCR} = $portId;
                }
            }
        }
```
Resulting in xml like this:
```
        <PORT>
          <CONNECTIONS>
            <CDP>1</CDP>
            <CONNECTION>
              <IFDESCR>ens255f0</IFDESCR>
              <SYSDESCR>Debian GNU/Linux 11 (bullseye) Linux 5.15.83-1-pve #1 SMP PVE 5.15.83-1 (2022-12-15T00:00Z) x86_64</SYSDESCR>
              <SYSMAC>2c:60:0c:da:79:61</SYSMAC>
              <SYSNAME>ceph-cl2-n5</SYSNAME>
            </CONNECTION>
          </CONNECTIONS>
          <IFALIAS>LA:ceph-cl2-n5-bond0:ae7</IFALIAS>
          <IFDESCR>xe-0/0/0</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>3177141320</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>17 hours, 00:08.10</IFLASTCHANGE>
          <IFMTU>9192</IFMTU>
          <IFNAME>xe-0/0/0</IFNAME>
          <IFNUMBER>513</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>1504076382</IFOUTOCTETS>
          <IFPORTDUPLEX>3</IFPORTDUPLEX>
          <IFSPEED>10000000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>c0:42:d0:18:2c:97</MAC>
        </PORT>
```


According to me, the if-statement prevents anything mac-like to be parsed, so I changed it to:
```
        # portId is either a port number or a port mac address,
        # duplicating chassisId
        my $portId = $lldpRemPortId->{$suffix};
        #if ($portId !~ /^0x/ or length($portId) != 14) {
        if ($portId !~ /^0x/ or length($portId) == 14) {
            my $maybe_mac = lc(alt2canonical($portId)) || lc(alt2canonical(getCanonicalString($portId)));
            $portId = getCanonicalString($portId);
            if ($portId =~ /^\d+$/) {
                $connection->{IFNUMBER} = $portId;
            } else {
                    #my $maybe_mac = lc(alt2canonical($portId));
                if ($maybe_mac) {
                    push @{$connection->{MAC}}, $maybe_mac;
                } else {
                    $connection->{IFDESCR} = $portId;
                }
            }
        }
```

Now the XML contains also "MAC" for the connection:
```
        <PORT>
          <CONNECTIONS>
            <CDP>1</CDP>
            <CONNECTION>
              <IFDESCR>ens255f0</IFDESCR>
              <MAC>2c:60:0c:c0:ac:77</MAC>
              <SYSDESCR>Debian GNU/Linux 11 (bullseye) Linux 5.15.83-1-pve #1 SMP PVE 5.15.83-1 (2022-12-15T00:00Z) x86_64</SYSDESCR>
              <SYSMAC>2c:60:0c:da:79:61</SYSMAC>
              <SYSNAME>ceph-cl2-n5</SYSNAME>
            </CONNECTION>
          </CONNECTIONS>
          <IFALIAS>LA:ceph-cl2-n5-bond0:ae7</IFALIAS>
          <IFDESCR>xe-0/0/0</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>3853761513</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>17 hours, 00:08.10</IFLASTCHANGE>
          <IFMTU>9192</IFMTU>
          <IFNAME>xe-0/0/0</IFNAME>
          <IFNUMBER>513</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>2494522005</IFOUTOCTETS>
          <IFPORTDUPLEX>3</IFPORTDUPLEX>
          <IFSPEED>10000000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>c0:42:d0:18:2c:97</MAC>
        </PORT>
```

However, upon importing this resulting XML (which seems more correct), no LLDP connections are now linked at all, seems the "MAC" entry is wrong ==> should it replace sysmac?

**Comment by g-bougard** [comment] 2023-02-03 11:04
Commenting `my $maybe_mac ...` definition line and still using `$maybe_mac` after is a syntax error.
If you want to play with the code, you also need to understand how device linking is supported in GLPI and so you need to audit inventory code in GLPI.

In place of changing code and probably playing the wrong game. Try to understand the XML format, play eventually with it changing the XML and import it manually to see if there's something that should be handled differently.

But be careful, you're starting to make the problem more complex and I won't follow you if you're not giving the datas to make the problem reproducible.

**Comment by liedekef** [comment] 2023-02-03 11:24
I think you didn't notice this line:

`            my $maybe_mac = lc(alt2canonical($portId)) || lc(alt2canonical(getCanonicalString($portId)));`

I've defined maybe_mac a bit higher to work on the unmodified $portId (before getCanonicalString changes it). This does produce the "nice" mac.
However, if you can tell me how the XML needs to be changed to allow linking, I'm more than happy to try anything. I'm currently trying to import after each change (and undoing changes to make sure I don't change 2 things at once), but no luck in the linking so far.

**Comment by liedekef** [comment] 2023-02-03 12:40
Can you communicate a place where I can share the xml-files (I don't want them to be visible on github as a whole ...)?

**Comment by g-bougard** [comment] 2023-02-06 09:09
You can send them to me privately by email to **gbougard** `at`**teclib** `dot` **com**. Can you then also provide a [full snmpwalk output](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output) of the problematic device ?

**Comment by liedekef** [comment] 2023-02-06 14:02
I've sent the info as requested (including the snmpwalk). Concerning the snmpwalk: I didn't add the timeout of 15 seconds, since that would not allow a full walk of ".1" to complete. However, I don't think the agent does a full ".1" walk, so that's not an issue I'd say.

**Comment by g-bougard** [comment] 2023-02-07 19:12
Hi @liedekef 
thank you for the datas sharing. I took some time to investigate what's going on.
I saw one thing: `ge-0/0/10.0` port exists on the srx, but it is of type 53 which is not imported by default as a "propVirtual" type. If I reconfigure GLPI to import port of type 53 as aggregate, I can see the devices linked after using your original XMLs but of course with a lot of ports as many are virtual.
In details, only looking at XML files:
 * On qfx one, I see the srx `ge-0/0/10.0` port connected to qfx `ge-0/0/46` port
   * `ge-0/0/10.0` is of type 53 in srx XML and has no connection
   * `ge-0/0/46` is of type 6 in qfx XML which is imported by default
 * On srx one, I see the qfx `ge-0/0/46` port connected to srx `ae5.0` port
   * `ae5.0` port is of type 161 or "ieee8023adLag" and is not imported by default and indeed it seems to be an aggregate or port10 & port11 when looking deeper.

Here is all the complexity of properly connecting devices. This need some more investigation and my guess is the agent should probably include some logic to found on which physical port we should really add a connection. The problem here is LLDP seems to report a connection with a remote port which is indeed not physical.

Actually, I don't see how cleanly merge datas which are not really meaningful. I just see we should probably handle the `lldpRemChassisIdSubtype` to cleanly read `lldpRemChassisId` as Mac address or what ever in place of guessing what it could be. From the qfx view `lldpRemChassisIdSubtype` for `ge-0/0/10.0` is indeed "7" for "local". And I think it means this is a value set locally on the remote device... some kind of virtual link and we know nothing about it from the lldp point of view. So, for this particular link, I don't see any way to figure out which remote physical port it is.

We can't assume `ge-0/0/10.0` is linked to `ge-0/0/10` physical port as we are not even aware of that port from the qfx.

**Comment by liedekef** [comment] 2023-02-07 19:54
Yeah, LACP and aggregated connections are a real hassle via lldp it seems. I'm not a junos expert (not even that proficient in networking), but could changing the lldp config on the srx/qfx help in any way?
And while I'm not that good in juniper stuff, I am reasonable ok in perl and php, so if you want me to test things/code, feel free to point me to a changeset to implement :-)

**Comment by g-bougard** [comment] 2023-02-08 12:36
Well, I'm starting to hate Juniper devices as I see another trouble on the srx.
Actually, in the srx, the LLDP table reports 2 connections on port 614 (the same for ports 533, 613 & 615):
```
.1.0.8802.1.1.2.1.4.1.1.4.90.614.8 = INTEGER: 4
.1.0.8802.1.1.2.1.4.1.1.4.90.614.9 = INTEGER: 4
.1.0.8802.1.1.2.1.4.1.1.5.90.614.8 = Hex-STRING: D8 18 D3 60 E5 80 
.1.0.8802.1.1.2.1.4.1.1.5.90.614.9 = Hex-STRING: D8 18 D3 60 E5 80 
.1.0.8802.1.1.2.1.4.1.1.6.90.614.8 = INTEGER: 7
.1.0.8802.1.1.2.1.4.1.1.6.90.614.9 = INTEGER: 7
.1.0.8802.1.1.2.1.4.1.1.7.90.614.8 = Hex-STRING: 35 30 39     -> This is port 509 on remote device
.1.0.8802.1.1.2.1.4.1.1.7.90.614.9 = Hex-STRING: 35 31 31     -> This is port 511 on remote device
```
Of course, theses ports are aggregates so I can understand we have 2 connections. Looking in ifStackTable (` .1.3.6.1.2.1.31.1.2`) I can find which physical ports which are related to 614 so I could probably better choose to add the connection to a physical port. And I can see physical ports are 514 ou 515.
But anyway, I don't see right now any rule which can tell me if remote port 509 is linked to local port 514 or port 515.
I can decide to arbitrarily link the first port here the "8" in the LLDP with 514 as first & "9" to 515 so remote port 509 would be linked to local 514 & remote port 511 to local port 515. So to resume:
 - local port 514 (ge-0/0/4) would be connected to remote port 509
 - local port 515 (ge-0/0/5) would be connected to remote port 511

With the same logic, for aggregate port 533:
 - local port 520 (ge-0/0/8) would be connected to remote port 510
 - local port 521 (ge-0/0/9) would be connected to remote port 508

For aggregate port 613:
 - local port 511 (ge-0/0/3) would be connected to remote port 511
 - local port 518 (ge-0/0/2) would be connected to remote port 509

In that last case, physical port 2 has a higher logical number than physical port 3. If the logic is wrong here, this may mean the connection in LLDP are ordered by physical port.

For aggregate port 615:
 - local port 516 (ge-0/0/6) would be connected to remote port 510
 - local port 517 (ge-0/0/7) would be connected to remote port 508

Would you please tell me how theses ports are really and physically connected to the remote devices ? So maybe I can implement an algorithm which will better associate connections to the underlying physical port.

**Comment by liedekef** [comment] 2023-02-09 08:40
I'll mail the 'show configuration interfaces' output from the 2 devices.
Also, from my network colleague: in "ge-0/0/10.0" the ".0" is a unit, which points to a virtual interface on ge-0/0/10. The unit is used to create a virtual interface linked to one or more vlans (see the config).

**Comment by g-bougard** [comment] 2023-02-09 11:25
Hi @liedekef 

thank you for the sharing.

Anyway, you shared the device config of the 2 devices... Firstly, this is not exactly what I requested in my last comment. I was talking about srx aggregate ports on which I see 2 remote devices in the walk (as I can expect) and I want to know which underlying physical port is connected to which remote physical port. So the request didn't concern the qfx, but the srx and 4 others devices. If you don't know how you can tell me which physical ports are inter-connected, you can also provide me the 4 others devices snmpwalks so I can try to find the information in the LLDP tables.

Indeed I want to be able to move detected connections in the inventory from the virtual port to the physical port. As by default only physical ports are imported in GLPI, this means only the related connections will be finally imported. The result may not be perfect but it may help at least when importing the srx. It may not help when importing the qfx as LLDP connection reports a virtual port but the srx support with its virtual ports configuration is part of the problem we can still enhance.

**Comment by g-bougard** [comment] 2023-02-09 18:21
Hi @liedekef 
can you test the [Hardware.pm](https://raw.githubusercontent.com/glpi-project/glpi-agent/f269798c3ef8a805f375934c806911189447928e/lib/GLPI/Agent/Tools/Hardware.pm) module from f269798 ? 
It should help you to see more connections in the port view, at least on the srx. But I don't think it help to connect ports.
This version copy detected LLDP connections on the physical port too. As I said, I'm making some assumption for the ports which are aggregated so maybe the shown ones are exchanged.

I'm thinking to add a Juniper specific rule where I detects SYSDESCR starts with `Juniper` and IFDESCR ends with `.0` on detected LLDP connections. And so just remove the `.0`. Do you think this can help ?

**Comment by g-bougard** [comment] 2023-02-09 18:41
The other patch could be like this:
```diff
diff --git a/lib/GLPI/Agent/Tools/Hardware.pm b/lib/GLPI/Agent/Tools/Hardware.pm
index 28a77aa61..d9c9c795a 100644
--- a/lib/GLPI/Agent/Tools/Hardware.pm
+++ b/lib/GLPI/Agent/Tools/Hardware.pm
@@ -1342,6 +1342,12 @@ sub _getLLDPInfo {
             }
         }
 
+        # Handle specific Juniper case where shown IFDESCR is indeed a virtual port
+        if ($connection->{SYSDESCR} =~ /^Juniper/ && $connection->{IFDESCR} =~ /\.0$/) {
+            # Transform IFDESCR to point physical port and not virtual one
+            $connection->{IFDESCR} =~ s/\.0$//;
+        }
+
         my $id           = _getElement($suffix, -2);
         my $interface_id =
             ! exists $port2interface->{$id} ? $id                   :
```
IFDESCR is correct in the connection but this doesn't seem to help to create a link between the 2 devices ports. Something seems wrong with the seen Mac in LLDP.

**Comment by liedekef** [comment] 2023-02-10 08:59
I don't think removing ".0" is enough, changing 0 by \d should be more generic. I'll test the new Hardware.pm (with the extra fix)

**Comment by liedekef** [comment] 2023-02-10 12:18
I've tried the new Hardware.pm (without the extra code to remove the unit-number). The XML generated seems ok, but on the GLPI server I don't see any aggregated devices (the ae* ones) nor the virtual ones. It seems for some reason those are ignored ... I'll email you the generated XML of the srx again.

**Comment by g-bougard** [comment] 2023-02-10 17:26
The aggregate ports are virtual on your Juniper configuration and so they are not imported as the virtual ports are not set to be imported by default. If you want to import them, you'll a lot more ports than just the physical ones. That's up to you if you really need to see them in GLPI.

**Comment by liedekef** [comment] 2023-02-13 12:36
Upon network inventory of the discovered devices, a number of ae* devices get created as "unmanaged", I'm a bit unsure as why that happens, as I can see some ae-device in unmanaged with correct LLDP info added to it. Also a number of "hub" devices get created: it seems for each lldp-discovered connection that has CDP set to 1, a hub link gets created and added to a hub-device. For the record: we don't have any hubs :-)  I've yet to verify if my statement is true, but after network discovery I had 7 network devices added, and after network inventory all of the sudden a number of HUB and ae* devices get added in Unmanaged. The ae-devices in the unmanaged section clearly belong to one or another network device, but can't seem to get linked/added there. The HUB devices are even more weird ...

I updated to glpi-nightly to see if any difference: none.

**Comment by g-bougard** [comment] 2023-02-22 15:28
@liedekef 
just a note here, I still didn't merge my patch proposal on nightly build. It is still one commit on [update-juniper-lldp-support](https://github.com/glpi-project/glpi-agent/tree/feature/update-juniper-lldp-support) branch.

**Comment by liedekef** [comment] 2023-02-22 18:59
I'll try those changes tomorrow, didn't realize that it wasn't in :-)

**Comment by liedekef** [comment] 2023-02-23 13:37
currently I don't see many improvements in GLPI itself (but I may be blind here ...). GLPI still reports the "10.0" and also hubs (???). Would it help if I send you the new generated xml's for the srx and the qfx via mail?

**Comment by g-bougard** [comment] 2023-02-23 14:13
You told to enable the import of virtual ports type created by your Juniper devices (Type 53 & 161 if I remember well). IMHO, this is not a good idea as you'll have a lot of ports which are not physical. My patch was essentially to bind the connection to the related physical port so you don't need to import virtual ports and I maybe hubs are related to virtual ports.
I don't need the XML as I can generate them from the walks you provided.

**Comment by liedekef** [comment] 2023-02-23 14:29
I indeed import 161 (aggregated ports), but not 53 (that was indeed giving too much). I'll disable 161 again

**Comment by liedekef** [comment] 2023-02-23 14:39
After disabling 161, in the network overview of testlab-srx: I no longer see any LLDP connections. There is one network connection called "vlan" (value 507), connected to an unmanaged device (hub), that has like 318 connections in total (many of which are in fact lldp connections, but also from other devices besides the testlab-srx). Next to that (and the fact that things are going into unmanaged), no other LLDP connection is shown anymore.
The qfx-network overview shows some LLDP connections, but also not everything LLDP-connected to it (and it refers to "10.0" as a port on the srx, but that one was known for now).

**Comment by g-bougard** [comment] 2023-02-23 16:50
Just added the other patch to the branch: bbe03f3
This is the one to cleanup the SYSDESCR from virtual part.
Don't know if this can really help.
Anyway, I think this will be hard to keep support for such exotic configuration. I'm really not sure to merge this patch in develop branch. Especially if this doesn't give you a really better support.

**Comment by liedekef** [comment] 2023-02-27 12:26
Besides the HUB-issue, this seems to help at least partially now.

**Comment by g-bougard** [comment] 2023-02-27 13:09
Hi @liedekef 
interesting.
I had to partially back-port the branch. You may want to compare the branch result with next nightly build. For now, I didn't back-port bbe03f3 and the part which add the connection to the physical port.
I had to make this back-port to avoid reported connection change between inventory runs.

**Comment by liedekef** [comment] 2023-02-28 12:47
New nightly build without further modifs:
- on the srx no lldp connections reported, except this vlan as a hub again:
![image](https://user-images.githubusercontent.com/75667/221857898-30dabc40-cefd-4c65-a9f6-06959dc4c5b1.png)
- on the qfx itself, there are less differences (the lldp connection 'testlab-srx >  ge-0/0/10.0' is reported there, as an unmanaged device, but that's a known thing)

**Comment by g-bougard** [comment] 2023-02-28 14:59
I rebased the dedicated [update-juniper-lldp-support](https://github.com/glpi-project/glpi-agent/tree/feature/update-juniper-lldp-support) branch against develop if you want to compare now.

**Comment by liedekef** [comment] 2023-02-28 15:23
using the branch: 

- the vlan "issue" stays (also: the "11 equipments connected in that hub is not really connect, since if I click on that "hub" it reports 318 connections :-) )
- on the srx: ge-0/0/10 is reported to be connected to the qfx (lldp)
- the qfx also reports to be connected to the srx (lldp), so that's ok too

**Comment by g-bougard** [comment] 2023-02-28 16:22
The vlan issue is weird and I don't reproduce it with the current walk you provided. Maybe this is a GLPI issue. You may want also to try current GLPI nightly as it includes some fixes related to Unmanaged devices support and network ports support.
Anyway, if it actually really helps, do you think the branch should be merged ?

**Comment by liedekef** [comment] 2023-03-01 09:10
I'm using the glpi version from 11 feb, I'll try updating again later on today.
However, I just did these steps:
- unlink the vlan hub from the "vlan" network on the srx
- cleaned all unmanaged devices
- redo a network inventory

Result:
- vlan hub doesn't get re-added ==> meaning: no correct update was done on the existing testlab-srx on previous runs?
- 7 unmanaged network devices get added, all called "testlab-srx", all with 1 one port connected (with also 1 LLDP connection on it):
ge-0/0/2
ge-0/0/3
ge-0/0/4
ge-0/0/5
ge-0/0/8
ge-0/0/9
ge-0/0/10
Now: the existing testlab-srx also has all these ports, but with a different MAC (probably some combined connection)
If these 7 were to be correctly added to the existing testlab-srx, the info would almost be complete :-)  Can glpi (and glpi-agent) handle this case?

**Comment by liedekef** [comment] 2023-03-02 15:08
Concerning the GLPI version to test: https://nightly.glpi-project.org/glpi/ ==> should I test "main" or 10-nightly?

**Comment by g-bougard** [comment] 2023-03-02 16:29
You should test with "10-nightly".

**Comment by liedekef** [comment] 2023-03-02 16:40
Ok, using the latest gpli-10 version (not main) and the latest agent, the same behaviour: ports get created in managed and unmanaged for the same device. An testlab-srx example:
-  in managed:
![image](https://user-images.githubusercontent.com/75667/222493217-b071da15-9b7b-48d9-b0d4-c45d0f28139e.png)
- in unmanaged:
![image](https://user-images.githubusercontent.com/75667/222493366-16c6ce4e-f490-4167-9c24-380bd29bc3cc.png)

There's some kind of mac-connection, so maybe related to the LA?
The same for the qrx:
- in managed:
![image](https://user-images.githubusercontent.com/75667/222493879-8deaa8e0-3122-4ac7-9bc0-7299e68d4066.png)
- in unmanaged:
![image](https://user-images.githubusercontent.com/75667/222493998-28d50a78-567e-45c5-a48a-e8f118509b52.png)

**Comment by g-bougard** [comment] 2023-03-07 16:54
Hi @liedekef 

for the first case:
 - the managed one comes from the testlab-srx import
 - the unmanaged one comes from the switch-r26.tl.belnet.be inventory import

As port description and mac are not matching, GLPI can't decide if `ge-0/0/5` should match. As I don't have the switch-r26.tl.belnet.be inventory details, I can't tell you if we should be able to have a match.

For the second case:
 - here the managed one comes from the qfx import. SYSMAC is set on the connection and seems not to match the srx port.
 - the unmanaged one comes from the connection found on the ge-0/0/10 during testlab-srx import

Here only the mac is different and this means GLPI still can't decide the ports match.

In my point of vue, LLDP support is really limited with Juniper devices and we should probably not merge the PR as this doesn't really help. Maybe there's some configuration in related Juniper devices to make LLDP support more standard.
My guess is you'll just have to manage the ports links manually for that Juniper devices.

**Comment by g-bougard** [comment] 2023-09-06 08:46
Hi @liedekef 

I'm closing this old issue. Feel free to reopen and/or comment if you have any update that could help to address such problem.

**Closed as completed by g-bougard** 2023-09-06 08:46 UTC
Labels: bug
