### ISSUE TITLE
PC with Windows 8.1 not being inventoried

### ISSUE THREAD

**Issue by demimurr** [glpi-project/glpi-agent#161] opened 2022-06-30 06:04 UTC
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

After installing the agent on the computer, I see the agent, but there is no connection with any computer, the computer does not appear in the list.
Window XP, 7, 10 is OK

### To reproduce

Install on PC GLPI-Agent-1.3-x64
Force inventory

### Expected behavior

Creatin new PC object

### Operating system

Windows

### GLPI Agent version

1.3, 1.2

### GLPI version

10.0.1

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0

**Comment by g-bougard** [comment] 2022-06-30 08:15
Hi @demimurr 

can you provide any agent log showing there's a problem on this platform ? You should probably enable debug=2 in registry and restart the service to be sure.

A point, sometime people is not waiting enough time before checking. If you don't use the install option to "run now", the asset can take an hour before appearing in GLPI.

**Comment by demimurr** [comment] 2022-06-30 08:42
Problem on 6 PCs, all with Win 8.1. No one computer with win 8.1 has been inventoried. The agent appeared on the server, but there is no connection with any computer. I do not know what the problem is in the server or in the agent on the computer
![image](https://user-images.githubusercontent.com/108415564/176632342-14841731-e49c-4b8a-8e71-a56219daa486.png)

**Comment by g-bougard** [comment] 2022-06-30 09:54
Oh, the problem is probably different. The agent is running and contact the server to submit its inventory. Now GLPI server probably just reject the inventory for some reason. You should have catch that information if you have checked the agent log. So can you check the agent log like I requested and share any error from the server you see while the agent is submitting its inventory ? Or share the part the inventory is submitted and the server saying its okay.

**Comment by g-bougard** [comment] 2022-08-10 16:18
Closing without issuer feedback.
@demimurr feel free to reopen if you have some agent log to share.

**Closed as completed by g-bougard** 2022-08-10 16:18 UTC
Labels: help wanted

**Comment by masterbbgit** [comment] 2022-09-09 07:00
I confirm the error on all Windows 8.1 PCs (works fine on other OS)
[Fri Sep  9 11:32:54 2022][info] target server0: server http://_~glpi~_/
[Fri Sep  9 11:32:54 2022][info] sending contact request to server0
[Fri Sep  9 11:32:55 2022][info] running task Inventory
[Fri Sep  9 11:32:55 2022][info] New inventory from _MP.mp_-2022-09-09-11-06-11 for server0
[Fri Sep  9 11:33:14 2022][error] [http client] communication error: 500 Internal Server Error

**Comment by g-bougard** [comment] 2022-09-09 07:47
Hi @masterbbgit 
please, can you enable debug=2 in registry, restart the service and share the log around the error ? Can you confirm also your glpi-agent version ? Can you confirm you're not using https ?

**Comment by masterbbgit** [comment] 2022-09-09 08:15
Yes, we do not use https
version glpi agent 1.4 or last nightly build 1.5 (x64 - x86)
[glpi-agent.log](https://github.com/glpi-project/glpi-agent/files/9533613/glpi-agent.log)

**Comment by g-bougard** [comment] 2022-09-09 11:37
Well, generally, `500 Internal Server Error` means there's a problem on server-side. Do you see any related error in your httpd server log where GLPI is hosted ?

Can you try to locally generate the json file with `glpi-inventory --json >inventory.json` and use `glpi-injector -v --debug -f inventory.json -u http://your-glpi/` to inject it ? Do you also have an error ?

That will be hard to find a windows 8.1 to make some tests ^^

**Comment by masterbbgit** [comment] 2022-09-09 11:58
json is uploaded to the server, but for Windows 8.1 - to the wrong partition (correct /computer/0 - for other OS)
Windows 8.1
![изображение](https://user-images.githubusercontent.com/65221077/189343890-a83d9124-2542-4419-8036-246037e97e1a.png)

otherOS
![изображение](https://user-images.githubusercontent.com/65221077/189343625-67e1b9c4-153c-4f3b-89da-f268006ae1e1.png)
there is no binding of the agent to the equipment?
I will follow your instructions later. I will follow your instructions later. After the end of the working day.
While writing, I discovered that the rights of the folders are different

**Comment by masterbbgit** [comment] 2022-09-12 05:16
clients windows 8.1, run force an inventory (web):

error log apache:
[php7:notice] [pid 1785] [client 192.1.2.30:63825] PHP Notice:  Undefined index: glpiname in /var/www/glpi/src/CommonDBTM.php on line 4467
[Mon Sep 12 09:52:18.182866 2022] [php7:notice] [pid 1785] [client 192.1.2.30:63825] PHP Notice:  Undefined index: nok_3HVhd68ptt$$$$783 in /var/www/glpi/src/Inventory/Asset/Software.php on line 676
[Mon Sep 12 09:52:18.183124 2022] [php7:error] [pid 1785] [client 192.1.2.30:63825] PHP Fatal error:  Column 'softwares_id' cannot be null in /var/www/glpi/src/DBmysql.php on line 1953
[Mon Sep 12 09:52:55.160397 2022] [php7:notice] [pid 2286] [client 192.1.2.30:64004] PHP Notice:  Undefined index: glpiname in /var/www/glpi/src/CommonDBTM.php on line 4467
[Mon Sep 12 09:52:56.711886 2022] [php7:notice] [pid 2286] [client 192.1.2.30:64004] PHP Notice:  Undefined index: nok_8iNqwG1tNh$$$$783 in /var/www/glpi/src/Inventory/Asset/Software.php on line 676
[Mon Sep 12 09:52:56.712271 2022] [php7:error] [pid 2286] [client 192.1.2.30:64004] PHP Fatal error:  Column 'softwares_id' cannot be null in /var/www/glpi/src/DBmysql.php on line 1953

access log apache:
192.1.2.30 - - [12/Sep/2022:09:52:11 +0500] "POST / HTTP/1.1" 500 391 "-" "GLPI-Agent_v1.5-git0ab78abf"
192.1.2.31 - -[12/Sep/2022:09:52:26 +0500] "POST / HTTP/1.1" 500 391 "-" "GLPI-Agent_v1.4"

php_errors.log (php 7.4)
[2022-09-12 09:52:56] glpiphplog.ERROR:   *** PHP User Error (256): Column 'softwares_id' cannot be null in /var/www/glpi/src/DBmysql.php at line 1953
  Backtrace :
  src/DBmysql.php:1953                               trigger_error()
  src/Inventory/Asset/Software.php:708               DBmysql->executeStatement()
  src/Inventory/Asset/Software.php:385               Glpi\Inventory\Asset\Software->storeVersions()
  src/Inventory/Asset/MainAsset.php:811              Glpi\Inventory\Asset\Software->handle()
  src/Inventory/Asset/MainAsset.php:731              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:945                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:550              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:697                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:331                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:325    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:237    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  index.php:94                                       include_once()
script create temp json in folder ./glpi/files/_inventories/ and stop


> Can you try to locally generate the json file with `glpi-inventory --json >inventory.json` and use `glpi-injector -v --debug -f inventory.json -u http://your-glpi/` to inject it ? Do you also have an error ?


Yours command is WORKS!!! (with user rights)
Loading c:\temp\inventory.json...[F9287F29] [agentid:a8749977-6bf5-1014-bf0c-ec5
44ccda770] OK
DEBUG: {"expiration":24,"status":"ok"}
![изображение](https://user-images.githubusercontent.com/65221077/189578442-6e746a51-d81c-4054-b414-b6dcc80dbad0.png)

with system rights (default services) not work

C:\>"c:\Program Files\GLPI-Agent\glpi-injector.bat" -v --debug -f c:\temp\inventory.json -u http://urlglpi/
Loading c:\temp\inventory.json...[8E045065] [agentid:b603787f-6bf9-1014-adb2-813c09637aeb] ERROR: Unexpected empty server response
These elements were not sent:
c:\temp\inventory.json

logs are the same

As a temporary solution, in the domain, when the user logs in, execute the following commands in sequence:
"c:\Program Files\GLPI-Agent\glpi-inventory.bat" --json >c:\temp\inventory.json
"c:\Program Files\GLPI-Agent\glpi-injector.bat" -f c:\temp\inventory.json -u http://urlglpi/

for autoit:
If @OSVersion = 'WIN_81' Then
	If FileExists('c:\Program Files\GLPI-Agent\glpi-inventory.bat') Then
	RunWait(@ComSpec & ' /c ' & '"c:\Program Files\GLPI-Agent\glpi-inventory.bat" --json >c:\temp\inventory.json','', @SW_HIDE)
	RunWait(@ComSpec & ' /c ' & '"c:\Program Files\GLPI-Agent\glpi-injector.bat" -f c:\temp\inventory.json -u http://urlglpi/','', @SW_HIDE)
	EndIf
EndIf

p.s: the temp folder and glpi url must be replaced with your own parameters

**Comment by g-bougard** [comment] 2022-09-12 06:45
Hi @masterbbgit 
it seems you have errors in GLPI which are probably the source of the `500 Internal Server Error`. What version are you using ?
About the glpi-injector, it works the same if run with or without system rights. I think your real problem is your GLPI.

**Comment by masterbbgit** [comment] 2022-09-12 06:49
> What version are you using ?

10.0.2 (migrate 9.5.8->10.0.1->10.0.2)


> About the glpi-injector, it works the same if run with or without system rights. I think your real problem is your GLPI.

other OS (MS server/XP/7/10/11, freeebsd/nix) work correctly

@g-bougard thank you very much - i use your solution

**Comment by galarov** [comment] 2022-10-14 09:49
Hello,

I've got the same problem with glpi-agent on Windows 8.1.

GLPI Server: GLPI 10.0.2
GLPI Agent: GLPI-Agent-1.4

Problem is as stated above: After installing the agent on a computer with Windows 8.1 inventorisation is done allright, but there is an error when the computer is trying to send the report to the server. I observe this problem on all Windows 8.1 computers (100+). 

The GLPI installation is fresh - no upgrades or other modifications was applied. Just installed the serve, deployed agents and ran into this issue.

Agent side: glpi-agent log:

[Wed Oct 12 20:57:34 2022][info] target server0: server https://inventory.openbit.ru:40443/front/inventory.php
[Wed Oct 12 20:57:34 2022][info] sending contact request to server0
[Wed Oct 12 20:57:35 2022][info] running task Inventory
[Wed Oct 12 20:57:35 2022][info] New inventory from WS37-2022-10-12-13-06-34 for server0 (tag=ARKADIA)
[Wed Oct 12 20:58:02 2022][error] [http client] authentication required, error status: 500 Internal Server Error
[Wed Oct 12 20:58:04 2022][info] target server0: next run: Thu Oct 13 20:10:55 2022 - https://inventory.openbit.ru:40443/front/inventory.php
[Wed Oct 12 20:58:04 2022][info] GLPI Agent memory usage: WSS=3297280 PFU=145129472

Server side: /var/log/httpd/ssl_error_log:

[Wed Oct 12 20:57:10.451317 2022] [php:warn] [pid 34937] [client 176.32.182.186:50778] PHP Warning:  Undefined array key "nok_hRVuvKpgZp$$$$927" in /var/www/glpi/src/Inventory/Asset/Software.php on line 676
[Wed Oct 12 20:57:10.451621 2022] [php:error] [pid 34937] [client 176.32.182.186:50778] PHP Fatal error:  Column 'softwares_id' cannot be null in /var/www/glpi/src/DBmysql.php on line 1953

A workaround.

One way to get around this problem is to disable sending software category by the agent: "no-category REG_SZ software". In this case Windows 8.1 computers appear on the server and all inventory data is in place except for Software offcourse.

Another way is like you mentioned above:

"c:\Program Files\GLPI-Agent\glpi-inventory.bat" --json >c:\temp\inventory.json
"c:\Program Files\GLPI-Agent\glpi-injector.bat" -f c:\temp\inventory.json -u https://glpi_perseygroup_user:password@inventory.openbit.ru:40443/front/inventory.php

When I use glpi-injector.bat, the report is sent to the server without issue. The computer appears on the list. But we use a number of Entities. Rules put computers into respective Entities according to "Inventory TAG". So, when I run glpi-injector.bat, TAG is not being set and the computer appears in Root entity. So it's not good. 

I would appreciate any ideas how to fix it.

Thank you.

Best regards,
Alexey Bystrov
