### ISSUE TITLE
Error JSON does not validate 'interface' storage property on win32

### ISSUE THREAD

**Issue by tdelaux** [glpi-project/glpi-agent#231] opened 2022-10-10 15:23 UTC
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Hello,
Always the same error than : https://github.com/glpi-project/glpi-agent/issues/207

GLPI Agent don't create/update computer into GLPI.

The GLPI Agent is correctly created in GLPI, but not the computer.

glpi-agent.log contains the following error lines :

[Mon Oct 10 17:15:58 2022][error] [http client] communication error: 500 Internal Server Error
[Mon Oct 10 17:15:58 2022][debug2] format: Zlib
[Mon Oct 10 17:15:58 2022][debug2] [http client] 2A5BEBBA: received message:
{"status":"error","message":"JSON does not validate. Violations:\n\"NVME\" does not match to ^(SCSI|HDC|IDE|USB|1394|SATA|SAS|ATAPI)$ at #->properties:content->properties:storages->items[0]:0->properties:interface\n","expiration":24}
[Mon Oct 10 17:15:58 2022][error] [http client] 2A5BEBBA: server error: JSON does not validate. Violations:
"NVME" does not match to ^(SCSI|HDC|IDE|USB|1394|SATA|SAS|ATAPI)$ at #->properties:content->properties:storages->items[0]:0->properties:interface

### To reproduce

 "controllers": [
         {
            "caption": "NVMe SSD Controller PM9A1/PM9A3/980PRO",
            "manufacturer": "Samsung Electronics Co Ltd",
            "name": "NVMe SSD Controller PM9A1/PM9A3/980PRO",
            "pcisubsystemid": "144d:a801",
            "productid": "a80a",
            "type": "Standard NVM Express Controller",
            "vendorid": "144d"
         },

### Expected behavior

try again ;-)

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.3

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.4

**Comment by g-bougard** [comment] 2022-10-10 15:37
Hi @tdelaux 
as explained in #220, the fixed file was not included in GLPI 1.0.3. Definitively, it will be in 1.0.4.
You still can fix the problem following my comment on [#207](https://github.com/glpi-project/glpi-agent/issues/207#issuecomment-1239610042).

**Closed as completed by g-bougard** 2022-10-10 15:37 UTC
Labels: bug

**Comment by tdelaux** [comment] 2022-10-10 15:40
Sorry, I thought the next version was 10.0.3 ;-(((

**Comment by g-bougard** [comment] 2022-10-10 17:56
It was at the time of #207.
But sorry, we missed to include the fixed file in that release.
I can guarantee you the fixed file is still included for next release.

**Comment by GuilhermeSt12** [comment] 2023-08-28 18:33
Já faz um ano desde a primeira solicitação desse erro. Há alguma previsão ou outra alternativa de solução?

**Comment by g-bougard** [comment] 2023-08-29 06:38
As explained when I closed this issue, the problem is fixed in GLPI 10.0.4. If you're still with earlier versions, please upgrade.
