### ISSUE TITLE
GLPI agent considered as a threat by AVAST Antivirus

### ISSUE THREAD

**Issue by rich-gg** [glpi-project/glpi-agent#116] opened 2022-05-05 04:57 UTC
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

I have been trying to get the GLPI agent to run on my machines and AVAST
is not letting it do its things*

it says GLPIAgent uses IDP.HELU.PSE27

First it simply deletes glpi-agent.exe (no possibility to revers and create an exception)
Then it blocks powershell.exe

*as stated here : https://forum.glpi-project.org/viewtopic.php?pid=491480#p491480

ps: I ran a malwarebytes scan on those machine and no malware detected

### To reproduce

On a PC equiped with AVAST Free

install GLPI agent using the vbs script
OR
install GLPI agent simply using the  GLPI-Agent-1.2-x64.msi

### Expected behavior

- Installation run smoothly
- Then the Avast alerte pops up, telling about the glpi-agent.exe
- > no data is sent to the server

- the next day , another Avast alerte pops up with and alerte about powershell.exe

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

10.0.0

### GLPIInventory plugin or FusionInventory for GLPI plugin version

9.4+2.6

**Comment by g-bougard** [comment] 2022-05-05 07:15
Hi @rich-gg 

thank you for the triggering, this should of course be false positive unless you had a virus that infected the agent after its installation.

Some AV are doing more and more bullshit, that's a shame. Very few AV made troubles with GLPI Agent 1.2.

Anyway I made a submission to AVG "suspected false positive" form.

If I refer to the forum thread you linked, it seems you're thinking you "must" uninstall fusioninventory-agent to use glpi-agent. This is not an obligation. GLPI 10 still supports fusioninventory agent as inventory agent. GLPI Agent has just more fixes you may need than FusionInventory agent has.

We can't do more at that time. So I'm closing the issue, but feel free to comment if an AVAST database update finally makes the agent works normally.

**Closed as completed by g-bougard** 2022-05-05 07:15 UTC
Labels: help wanted

**Comment by rich-gg** [comment] 2022-05-05 09:40
Hi @g-bougard 

I think it isn't write to close the issue that abruptly.
At the very least it should trigger an update to the documentation
specifying that GLPI doesn't work with Avast. 

It is understoud that this kind of issue is outside of the scope of
the strictly coding, but the issue is critical to many users, nonetheless.

**Comment by g-bougard** [comment] 2022-05-05 10:43
Hi @rich-gg 

as I told you, I submitted the case to AVAST so you're informed we're seriously taking this problem into account. The issue as itself is still taking part of the documentation. The problem needs right now to be managed by AVAST, and it is (I still had an answer showing there're investigating). Updating the documentation to specify that "GLPI doesn't work with Avast" won't happen as this is just a wrong sentence and the problem is temporary and only concern Avast & the agent (not GLPI server which is another product).

So please, don't be offended complaining about "abruptly" closed issue as I took time to analyze the subject and I even explain what is happening following your issue report.

You now just have to wait after AVAST database update. Just hope they understand detecting GLPI Agent as threat is critical for you or contact them yourself if this takes too much time.

Finally, the issue is just closed here as this is no more a GLPI Agent team problem.

**Comment by g-bougard** [comment] 2022-05-09 07:14
I had an update from AVG. They confirmed the false-positive and said they added an exclusion.
Can you confirm if you had a database antivirus update that fixes the problem ?
Thank you

**Comment by yanisvolteo** [comment] 2022-05-09 10:11
> 

bonjour, j'ai le même soucis que @rich-gg et la mise à jour de la base virale n'a rien changé.

**Comment by g-bougard** [comment] 2022-05-09 10:20
Hi @yanisvolteo 
do you have the glpi-agent.exe removed by the AV as it was reported (this problem should be fixed by database AV update) ? Or just the PowerShell.exe alerts (maybe not fixed by AV update) ?
I'll try to modify the way we uses PowerShell to not trigger the second case.

**Comment by yanisvolteo** [comment] 2022-05-09 10:28
> 
Non je n'ai plus le glpi-agent.exe supprimé par l'AV mais c'est car j'ai ajouté une exclusion. 

J'ai juste le deuxième cas avec le script PowerShell.

**Comment by g-bougard** [comment] 2022-05-09 17:57
Next nightly should fix the powershell problem.

**Comment by yanisvolteo** [comment] 2022-05-10 08:59
> Next nightly should fix the powershell problem.

super merci beaucoup, ça fonctionne !
