### ISSUE TITLE
Glpi agent get Wrong Serial Number canon 6030 Printer

### ISSUE THREAD

**Issue by oussamaess1958** [glpi-project/glpi-agent#281] opened 2022-12-01 14:44 UTC
### Bug reporting acknowledgment

Not applicable

### Describe the bug

Hello everyone,

We have many printers canon models  ( Canon M175, M176, IR2525, 6020,6030...).

The GLPI get the correct serial number of all printers except canon 6020 and 6030 , it get a wrong serial number

Example of one printer:
The serial number of printer is : NBFA252019
Serial number gated by GLPI agent : 0000A2F1R23J

how can i fix this probleme

best regards

### To reproduce

Execute new inventory by GLPI agent

### Expected behavior

wrong serial number

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.1

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0

**Comment by g-bougard** [comment] 2022-12-01 16:34
Hi @oussamaess1958 
for such kind of problem, we need a snmp walk of the device to reproduce.
The walk must be generated with a specific format: see [snmpwalk output documentation](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output)

**Comment by oussamaess1958** [comment] 2022-12-02 15:35
Hi @g-bougard 

Thank you for your response.

- My GLPI is deployed on Windows , please have you a documentation for windows ?
- The printers Canon 6020 and  6030 have not network port they are installed by port USB , does snmpwalk  work in my case ??

Sorry @g-bougard  i am beginner

**Comment by g-bougard** [comment] 2022-12-02 15:45
Hi @oussamaess1958 
sorry, my mistake, I thought you were talking problem with netinventory task.
Then, forget the snmp walk output request.
Can you share the output of the following command run in an administrative console and from the glpi-agent installation folder ?
```
glpi-inventory --partial printer
```

**Comment by oussamaess1958** [comment] 2022-12-04 07:45
Hi @g-bougard 

Thank you for the update.

kindly find in attachement the output of command and GLPI  agent  folder 

[glpi inventory cmd.txt](https://github.com/glpi-project/glpi-agent/files/10148069/glpi.inventory.cmd.txt)
[Glpi Agent.zip](https://github.com/glpi-project/glpi-agent/files/10148075/Glpi.Agent.zip)

**Comment by g-bougard** [comment] 2022-12-05 13:22
Hi @oussamaess1958 
please, don't share glpi agent installation folder archive. This is too much datas and really not useful.
What I see relevant in the command output is:
```
         {
            "driver": "Godex EZ2250i",
            "name": "Godex EZ2250i",
            "network": false,
            "port": "USB001",
            "printprocessor": "winprint",
            "resolution": "203x203",
            "serial": "1849059B",
            "shared": false,
            "status": "Idle"
         },
         {
            "driver": "Canon LBP6030/6040/6018L",
            "name": "Canon LBP6030/6040/6018L",
            "network": false,
            "port": "USB002",
            "printprocessor": "winprint",
            "resolution": "600x600",
            "serial": "0000A2F1R23J",
            "shared": false,
            "status": "Idle"
         },
```
These seem to be USB printer with a serial number. And this seems to be the second where you expected to have `NBFA252019`.

Can you confirm if the "Godex EZ2250i" print has really "1849059B" as serial number ?

Then to check what's going on I now need to have the output of the following command:
```
wmic path win32_printer get /format:list
```
I also see a registry export of the following registry keys:
```
HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Enum/USBPRINT
```
and
```
HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Enum/USB
```
If this is too heavy, you can only keep the entries related to the printer.

**Comment by oussamaess1958** [comment] 2022-12-05 14:37
Hi @g-bougard ,

Thank you for your diagnostic ,

Yes the serial number of Godex EZ2250i is also wrong , the reel serial number of Godex printer is " H118CV100F00138"
I think all usb printer have this problem
[Cmd glpi wmic.txt](https://github.com/glpi-project/glpi-agent/files/10155034/Cmd.glpi.wmic.txt)

In Attachement registe file and output of cmd



[Registe File.zip](https://github.com/glpi-project/glpi-agent/files/10155041/Registe.File.zip)
[Cmd glpi wmic.txt](https://github.com/glpi-project/glpi-agent/files/10155042/Cmd.glpi.wmic.txt)

**Comment by g-bougard** [comment] 2022-12-05 15:24
Hi @oussamaess1958 

thank you for that files. This really helps.

Actually, I can just say the 10 years old code which check that datas is just no more working with the current windows version in your case. It's time to upgrade that code...

Google-ing a little, I'm checking if I can make a big enhancement for that part. And I found some info telling the serial may possibly be retrieved from Win32_PnpEntity WMI objects. So can you share the output of the following command ?
```
wmic path Win32_PnpEntity get /format:list
```

**Comment by oussamaess1958** [comment] 2022-12-05 15:51
Hi @g-bougard 

Thank you for your quick response,

in attachement the output of Win32_PnpEntity

[Win32_PnpEntity.txt](https://github.com/glpi-project/glpi-agent/files/10155659/Win32_PnpEntity.txt)

**Comment by g-bougard** [comment] 2022-12-05 16:26
Thank you for the sharing.
Anyway, I don't see any related entry in this output. Are you sure to have get it from the same computer ? Are you sure the printer are connected and online ?
Also I see in the glpi-inventory output the computer is a "HP ZBook 15 G2" notebook. Are that notebook installed on a Dockstation ? If yes, can you try to connect the printer to a usb port of the computer in place to see if it appears in Win32_PnpEntity related output.

**Comment by oussamaess1958** [comment] 2022-12-05 19:13
sorry @g-bougard  I am not in my office tommorow i will connect to my printer and i will send you a new file

**Comment by oussamaess1958** [comment] 2022-12-06 09:17
Hi @g-bougard 

Now i connect to my printer Canon 6030 and i execute the command line  in attachement the output 

[Win32_PnpEntity 2.txt](https://github.com/glpi-project/glpi-agent/files/10164562/Win32_PnpEntity.2.txt)

**Comment by g-bougard** [comment] 2022-12-06 16:14
Hi @oussamaess1958 

sorry, this doesn't help: I can't see the expected serial number in the output.

Would you care to try this freeware tool: [USB Device Tree Viewer](https://www.uwe-sieber.de/usbtreeview_e.html)
Can you check if you find the Casio usb printer and check if the serial number is available somewhere ?
You can even eventually export a report and share it.

Can you tell us if you're able to see the printer S/N number somewhere in the system ? Maybe with a dedicated Casio software ?

**Comment by oussamaess1958** [comment] 2022-12-07 07:13
Hi @g-bougard 

I test with [USB Device Tree Viewer](https://www.uwe-sieber.de/usbtreeview_e.html)  and i have the same wrong serial number  (the correct serial number of Godex printer is H118CV100F00138)

  ---------------------- Device Descriptor ----------------------
bLength                  : 0x12 (18 bytes)
bDescriptorType          : 0x01 (Device Descriptor)
bcdUSB                   : 0x200 (USB Version 2.0)
bDeviceClass             : 0x00 (defined by the interface descriptors)
bDeviceSubClass          : 0x00
bDeviceProtocol          : 0x00
bMaxPacketSize0          : 0x40 (64 bytes)
idVendor                 : 0x195F (GODEX INTERNATIONAL CO., LTD.)
idProduct                : 0x0001
bcdDevice                : 0x0001
iManufacturer            : 0x10 (String Descriptor 16)
 Language 0x0409         : "GODEX INTERNATIONAL CO."
iProduct                 : 0x20 (String Descriptor 32)
 Language 0x0409         : "EZ2250i"
iSerialNumber            : 0x30 (String Descriptor 48)
 Language 0x0409         : "1849059B"
bNumConfigurations       : 0x01 (1 Configuration)
Data (HexDump)           : 12 01 00 02 00 00 00 40 5F 19 01 00 01 00 10 20   .......@_...... 
                           30 01                                             0.

This is the complete output 
[UsbTreeView.txt](https://github.com/glpi-project/glpi-agent/files/10173616/UsbTreeView.txt)

**Comment by g-bougard** [comment] 2022-12-07 08:43
Hi @oussamaess1958 

well, I guess something is just wrong with USB and the serialnumber is probably just the S/N of the USB interface.
Maybe the printer S/N can be retrieved by the driver but with private API that may be actually be used by manufacturer software. That's why I asked you the question if you're able to retrieve S/N somewhere, maybe by dedicated manufacturer software. Did you check that ?

As far I know, the S/N on usb devices is only usable for usb storage.

I'm sorry, I think we can't do anything more for S/N USB printers.

**Comment by oussamaess1958** [comment] 2022-12-07 10:08
Ok Thank you very much @g-bougard  for your help and your time

**Comment by g-bougard** [comment] 2022-12-07 15:12
Just in case, as customer of Casio & Godex, can you ask them how you can retrieve the printer serial number of USB printer (and if possible via a script) and share their response ?
So I'm closing the issue, but feel free to update it if you have any interesting information from manufacturers.
Also feel free to re-open if they provides a way to catch the S/N of usb printers.

**Closed as completed by g-bougard** 2022-12-07 15:12 UTC
Labels: bug, wontfix

**Comment by oussamaess1958** [comment] 2022-12-08 11:01
Ok thank you very much @g-bougard 
, but unfortunately we don't have a support contract with these manufacturers
