### ISSUE TITLE
Bad encoding in username during inventory

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi-agent#74] opened 2022-02-15 07:44 UTC
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

When the agent inventories a computer with a username containing accent, the encoding is broken in GLPI.

![image](https://user-images.githubusercontent.com/1759156/154015270-f78a1131-d8f8-4b09-a839-50eb877b96fb.png)

In the inventory json file:

![image](https://user-images.githubusercontent.com/1759156/154015393-951a9e5c-a8c7-4ab3-bf85-cfed59862369.png)

The encoding is broken in "softwares" too when the username appears.
It was working fine with GLPI 9.5.5 and Fusion Inventory.

### To reproduce

Inventories a computer with a logged user containing accent ex "frédéric"

### Expected behavior

Username should be frédéric not frÃ©dÃ©ric

### Operating system

Windows

### GLPI Agent version

1.1

### GLPI version

10.0.0-rc1

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0-rc4

**Comment by g-bougard** [comment] 2022-02-16 11:19
Hi @SteadEXE 

can you run the following command redirecting the output into a file on the platform where you have `Frédéric` logged or any user containing accent ?
```
wmic process where Caption="Explorer.exe" call GetOwner
```

**Comment by SteadEXE** [comment] 2022-02-16 11:47
I had to execute it remotely, in the shell accents were properly displayed but when redirected into a file everything was broken:
[wmic.txt](https://github.com/glpi-project/glpi-agent/files/8079570/wmic.txt)

User is not there yet

**Comment by SteadEXE** [comment] 2022-02-16 11:53
I just checked the history of the computer and:

![image](https://user-images.githubusercontent.com/1759156/154259336-6d2d55d6-cc06-4d85-bc9e-54b4abdb2dcc.png)

If you look closely, during the first inventory the computer was created with "frÃ©dÃ©ric" and has been changed to  "frédéric" the next day when inventory occured.

**Comment by g-bougard** [comment] 2022-02-16 14:27
Okay, maybe the error occurs when the inventory runs but the user is not logged, or only when it is logged. Do you think you can find in which case the problem occurs ?
Indeed, when the user is logged, the agent checks for the process owner of an `Explorer.exe` process. When it is not logged, it should check in registry.

**Comment by g-bougard** [comment] 2022-03-14 17:20
Hi @SteadEXE 
I wasn't able to reproduce this case. Does the history show the user changes between clean and badly encoded username ?

**Comment by SteadEXE** [comment] 2022-03-16 07:08
It only occured once, when I reported it. I don't know why it happened, it seems okay now.

**Comment by g-bougard** [comment] 2022-03-16 10:38
Hi @SteadEXE 
okay, then I'm closing the issue being unable to reproduce at the moment.
Feel free to reopen if you identify the context in which this happens.
I just hope this can arise during a temporary problem on the system involving the agent catches a badly encoded username but mainly get it right most of the time.

**Closed as completed by g-bougard** 2022-03-16 10:38 UTC
Labels: bug
