### ISSUE TITLE
Failure to detect memory slot size for VMware virtual machine with only one memory slot

### ISSUE THREAD

**Issue by ChristopheLacaze** [glpi-project/glpi-agent#571] opened 2023-12-27 14:45 UTC
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Memory slot size reported by glpi-agent for a Vmware virtual machine with 2 GB memory is wrong.
The value returned by the agent is 1732 (ie. hardware memory value) and not 2048 MB as returned by dmidecode

### To reproduce

Create a Vmware virtual machine with speciifcation :
- 2 Gb memory size
- 1 CPU
- Redhat family OS

execute glpi-agent

### Expected behavior

Glpi agent should report one 2048 MB size memory slot.

### Operating system

Linux

### GLPI Agent version

1.7

### GLPI version

10.0.x (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context

Here are results of dmidecode command and local inventory file generated on the virtual machine
[dmidecode-and-glpi-agent-inventory.zip](https://github.com/glpi-project/glpi-agent/files/13779330/dmidecode-and-glpi-agent-inventory.zip)

**Comment by g-bougard** [comment] 2024-06-07 13:03
Hi @ChristopheLacaze 

it seems I forgot to close this issue after I merged #572.

So I'm closing it now, but feel free to reopen if the problem is indeed not fixed.

**Closed as completed by g-bougard** 2024-06-07 13:03 UTC
Labels: bug
