### ISSUE TITLE
Just to signal about en error 400

### ISSUE THREAD

**Issue by daerlnaxe** [glpi-project/glpi-agent#314] opened 2023-01-10 19:09 UTC
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

I just had this a 400 error when sending informations to the GLPI server from the agent, and tried a lot of things without find a way until reading this [post](https://github.com/glpi-project/glpi-agent/issues/66).

### Bug
I tried with both machines below:
- VM on VMWare with Debian 11
- Host on windows 10

I tried a lot of urls without receiving any response on the Debian11 Client, then i installed on my Host.

I didn't find logs on Debian, i thought there were in /var/logs/ but no.

Finally i tried on windows and read logs to understand... I changed values in  the registry editor and after unsuccessful tries, by adding index.php at the end it worked.

### Solution
For both OS
add index.php at the end of the server url
My url: http://<server ip>/glpi/plugins/glpiinventory/index.php

i'm french, sorry for my english.

### To reproduce

Enter the url: http://<server ip>/glpi/plugins/glpiinventory/

### Expected behavior

Send informations about machine with the url given in the documentation

### Operating system

Windows, Linux

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.0.6

**Comment by g-bougard** [comment] 2023-01-11 08:11
Hi @daerlnaxe 
as said by @SteadEXE on #66:
> Okay it's propably because on IIS, when you post/put or whatever on the root of a directory, IIS uses a different handler.

Do you mean you installed GLPI on IIS ? You know we can't help you on IIS setup, but we can update documentation to alert people they can try another url when using IIS to host GLPI.

Also when submitting an issue, always share some log as they sometime contains helpful information.

**Comment by SteadEXE** [comment] 2023-01-11 08:50
Hi, I discovered what was the cause, by default IIS does not allow some HTTP verbs. 
When using the / instead of the full path, a different handle is used before transfering the request to the PHP handler.

This one only allows GET or something like this, I managed to update my IIS config to get it working, I will put it there if I can find what I changed. The current workaround is to use the full path with index.php as you did.

**Comment by SteadEXE** [comment] 2023-01-11 08:54
Ok I found it.

Go to your website in IIS.
Go to your handler mapping.

Double click on StaticFile.
Click the button restriction.
In the tab "verbs", do not use all but the list of verbs and put this: "GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD".

Sorry my screenshot is in french but it should does the trick.

![image](https://user-images.githubusercontent.com/1759156/211761260-23f7c2fe-d1b5-48e6-a3ce-540d1ca5a464.png)

**Comment by SteadEXE** [comment] 2023-01-11 09:03
@g-bougard I would like to update the doc, but I don't know where it would fit the best. 
I never used sphinx either.

I don't know if you want to add a mention by yourself, I can give you screenshots or more details if needed.

**Comment by g-bougard** [comment] 2023-01-11 09:06
Hi @SteadEXE 
many thanks for this detailed explanation.
Don't worry, I'll update the doc adding a warning and linking your post here.

**Comment by SteadEXE** [comment] 2023-01-11 09:08
I also updated my original post, so people with the same issue would find the fix aswell. The root issue is "All" not being really all in IIS. But that's a Microsoft issue 🥲

**Comment by g-bougard** [comment] 2023-01-11 09:31
Doc updated:
 * Caution added there: https://glpi-agent.readthedocs.io/en/latest/configuration.html#server
 * Related doc commit: [5e187fb](https://github.com/glpi-project/doc-agent/commit/5e187fba27f2393c93c00be997da24333fcedcc8)

**Comment by daerlnaxe** [comment] 2023-01-12 08:58
Hi @SteadEXE, i installed it on a fresh Debian 11, with Apache 2, PHP8.1 & MariaDB.

But when i read your post, even if i noticed it was about IIS i tried and it worked when all others addresses failed.

**Comment by g-bougard** [comment] 2023-01-12 10:48
Hi @daerlnaxe 
this still seems to be a server configuration issue.
So I'm closing this issue without bug evidence on agent side.

**Closed as completed by g-bougard** 2023-01-12 10:48 UTC
Labels: invalid

**Comment by daerlnaxe** [comment] 2023-01-12 14:22
I understand, it's more about the documentation i wrote this and to help others.

Thanks.
